In [1]:
import pandas as pd
import glob

In [2]:
path_stamps = glob.glob('/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/*')
path_stamps

['/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0025_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0000_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0003_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0042_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0019_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0033_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0028_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0017_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0032_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0023_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0024_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0004_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0010_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0011_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0041_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0001_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0035_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0022_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0021_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0007_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0026_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0014_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0009_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0037_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0008_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0038_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0012_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0018_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0005_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0013_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0015_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0027_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0030_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0002_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0036_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0031_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0029_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0020_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0006_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0016_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0039_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0034_stamps.pkl',
 '/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/chunk0040_stamps.pkl']

In [3]:
stamps = []
for path in path_stamps:
    stamps.append(pd.read_pickle(path))

stamps = pd.concat(stamps)
stamps

,oid,measurement_id,flux_Science_data,flux_Science_header,flux_Template_data,flux_Template_header,flux_Difference_data,flux_Difference_header,variance_Science_data,variance_Science_header,variance_Template_data,variance_Template_header,variance_Difference_data,variance_Difference_header,mask_Science_data,mask_Science_header,mask_Template_data,mask_Template_header,mask_Difference_data,mask_Difference_header
0,169342391392665651,169368779404869680,"[[-11.43412, -61.157898, -36.767532, 2.3479912...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[19.970436, 9.456891, 13.70118, 1.8506378, 5....","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-19.709507, -70.71258, -45.61192, -5.388886,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1350.7681, 1316.2396, 1328.7379, 1375.7206, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[48.75372, 48.6074, 44.92881, 53.182293, 40.7...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[1406.3743, 1370.4304, 1383.4205, 1432.3733, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.69...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.69...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
1,169342391392665651,169368781154418723,"[[12.617219, 24.45698, 35.47745, 10.133407, 73...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[9.981423, 20.141548, 23.992834, 33.55316, 59...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-17.836555, -11.826263, -7.5156693, -41.9118...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[172.93977, 179.61725, 185.36595, 171.49901, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[13.86152, 13.508177, 13.792195, 13.8862915, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[189.61496, 196.93031, 203.23215, 188.03621, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.58...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -2.02857206888...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.58...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
2,169342391396859977,169342391396859977,"[[20.201748, 8.987029, 20.140661, 5.541897, 2....","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[11.899033, 14.724549, 8.104676, 9.156919, 10...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[9.553257, -0.75593305, 11.6207695, -3.399367...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[113.74172, 110.11547, 114.21119, 107.290985,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[12.621083, 12.107674, 12.1881275, 14.158052,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[128.269, 124.173134, 128.77019, 121.12555, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.33...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.33...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
3,169342391461347756,169342391461347756,"[[7.650416, 16.770666, 41.501934, 16.376083, 2...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[21.86371, 25.689003, 24.45363, 27.604593, 15...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-18.728577, -10.020834, 17.58616, -11.041704...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[118.146385, 123.34396, 135.7948, 123.88186, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[13.748417, 16.173056, 14.099533, 15.934614, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[133.68181, 139.71996, 153.50385, 140.3026, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.47...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.47...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
4,169342391478124608,169342391478124608,"[[-12.872995, 7.4767823, 3.0093896, -14.866771...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-0.6696128, -4.0996137, -1.7693138, 4.084112...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-13.231101, 9.655578, 5.3894978, -14.162557,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[95.70028, 106.682724, 105.2998, 97.141594, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[9.187543, 11.646914, 14.130292, 10.453682, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[108.53373, 121.11635, 119.7852, 110.2706, 11...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.92...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.92...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,169562329003328119,169562329003328119,"[[-3.0328236, -64.28421, -59.547096, -95.51208...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[0.4429303, -2.1661365, -3.942304, -1.5371937...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-3.2889779, -62.43242, -53.27369, -86.90933,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2748.3682, 2767.9216, 2761.9822, 2680.687, 2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[22.411716, 19.57459, 25.457203, 24.962057, 2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[2681.8643, 2697.5452, 2698.4775, 2619.3398, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.73...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.73...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
99,169562329013813258,169562329013813258,"[[38.172523, 26.093853, 12.283279, -20.133076,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[13.483821, -0.6748158, -1.7875571, -5.311088...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[36.14181, 21.505014, 15.589528, -20.170776, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2506.3015, 2492.8352, 2515.6287, 2466.9817, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[30.414555, 24.478794, 21.991266, 23.258093, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[2446.2385, 2429.4968, 2450.0212, 2403.6978, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.4...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.4...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
100,169562329013813258,169593100545032234,"[[14.314384, -34.407063, 11.400057, 25.750315,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1.7783704, 4.489515, 23.06503, 7.888879, -1....","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2.6454637, -26.03307, 30.09177, 30.84492, -1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[640.8675, 615.82117, 642.30597, 649.9814, 63...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[76.7588, 76.76051, 69.82708, 69.882355, 66.0...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[728.3893, 703.3576, 721.8941, 729.62885, 706...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.15...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[5.170419506124674e-13, -1.2015745476460523e-...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.15...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
101,169562329091932561,169562329091932561,"[[-3.8693318, 2.9912574, -13.400819, -4.486403...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-2.0172863, -2.326338, -4.0626445, -1.336142...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[6.1452055, 6.9367323, -3.1461492, 2.352298, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2793.3806, 2776.2332, 2761.9338, 2785.414, 2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[22.012081, 22.856272, 22.025944, 21.95137, 3...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[2762.5725, 2748.5422, 2732.255, 2754.7, 2798...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 2.2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 2.2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
102,169562329102417949,169579900080488494,"[[71.2124, -59.137363, 7.426901, -32.388016, 3...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-15.60695, -13.921516, -21.890919, -16.37230...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[78.355125, -58.576157, 10.054412, -36.407543...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2951.7764, 2877.9316, 2949.492, 2871.1184, 2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[177.22978, 245.86554, 212.85515, 245.3349, 2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[3156.2275, 3082.4038, 3156.2983, 3075.11, 31...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.83...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.83...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."

In [4]:
test_predictions = pd.read_csv('test_predictions.csv')
oid_mid = (test_predictions.head(10).oid.values, test_predictions.head(10).measurement_id.values)
oid_mid

(array([169342391479697434, 169342391520592115, 169342391522689127,
        169342391608147991, 169342391654809731, 169342391672635395,
        169342391876059241, 169342391882874888, 169342391942644039,
        169342391999267256]),
 array([169342391479697434, 169342391520592115, 169364381640949779,
        169342391608147991, 169342391654809731, 169342391672635395,
        169342391876059241, 169342391882874888, 169342391942644039,
        169368781117194308]))

In [10]:
calibrated = pd.read_parquet('/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/models/experimentation/stamp_rubin/inference_output/2.0.0_eval/predictions_test.parquet')
calibrated

,oid,y_true_int,y_pred_raw_int,y_pred_cal_int,y_true_label,y_pred_raw_label,y_pred_cal_label,prob_AGN_raw,prob_AGN_cal,prob_SN_raw,prob_SN_cal,prob_VS_raw,prob_VS_cal,prob_asteroid_raw,prob_asteroid_cal,prob_bogus_raw,prob_bogus_cal
0,169342391479697434,4,4,4,bogus,bogus,bogus,0.159584,0.033594,0.157142,0.031312,0.206681,0.109249,0.157257,0.031417,0.319337,0.794428
1,169342391520592115,4,4,4,bogus,bogus,bogus,0.151660,0.013674,0.151382,0.013560,0.151779,0.013723,0.161621,0.018276,0.383560,0.940766
2,169342391522689127,4,4,4,bogus,bogus,bogus,0.153085,0.016315,0.152771,0.016163,0.167739,0.024753,0.155291,0.017415,0.371114,0.925354
3,169342391608147991,4,4,4,bogus,bogus,bogus,0.149545,0.010789,0.149471,0.010765,0.149762,0.010861,0.151415,0.011418,0.399808,0.956168
4,169342391654809731,4,4,4,bogus,bogus,bogus,0.170396,0.028475,0.155859,0.018961,0.155039,0.018510,0.153917,0.017907,0.364789,0.916147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784,169562328094736421,4,4,4,bogus,bogus,bogus,0.149167,0.010329,0.149079,0.010302,0.149382,0.010397,0.149529,0.010444,0.402842,0.958528
785,169562328094736476,4,4,4,bogus,bogus,bogus,0.149406,0.010588,0.149286,0.010550,0.149727,0.010693,0.150397,0.010912,0.401184,0.957257
786,169562328169709617,4,4,4,bogus,bogus,bogus,0.149602,0.010757,0.149420,0.010697,0.149625,0.010764,0.151096,0.011255,0.400257,0.956527
787,169562328976588853,4,4,4,bogus,bogus,bogus,0.150281,0.011637,0.150076,0.011564,0.150557,0.011734,0.154300,0.013124,0.394786,0.951941
788,169562328999133242,4,4,4,bogus,bogus,bogus,0.154072,0.018733,0.153784,0.018574,0.154153,0.018778,0.177083,0.035340,0.360907,0.908576

In [11]:
calibrated = calibrated[calibrated.oid.isin(test_predictions.head(10).oid.values)]
calibrated

,oid,y_true_int,y_pred_raw_int,y_pred_cal_int,y_true_label,y_pred_raw_label,y_pred_cal_label,prob_AGN_raw,prob_AGN_cal,prob_SN_raw,prob_SN_cal,prob_VS_raw,prob_VS_cal,prob_asteroid_raw,prob_asteroid_cal,prob_bogus_raw,prob_bogus_cal
0,169342391479697434,4,4,4,bogus,bogus,bogus,0.159584,0.033594,0.157142,0.031312,0.206681,0.109249,0.157257,0.031417,0.319337,0.794428
1,169342391520592115,4,4,4,bogus,bogus,bogus,0.151660,0.013674,0.151382,0.013560,0.151779,0.013723,0.161621,0.018276,0.383560,0.940766
2,169342391522689127,4,4,4,bogus,bogus,bogus,0.153085,0.016315,0.152771,0.016163,0.167739,0.024753,0.155291,0.017415,0.371114,0.925354
3,169342391608147991,4,4,4,bogus,bogus,bogus,0.149545,0.010789,0.149471,0.010765,0.149762,0.010861,0.151415,0.011418,0.399808,0.956168
4,169342391654809731,4,4,4,bogus,bogus,bogus,0.170396,0.028475,0.155859,0.018961,0.155039,0.018510,0.153917,0.017907,0.364789,0.916147
5,169342391672635395,4,4,4,bogus,bogus,bogus,0.159416,0.029187,0.156247,0.026634,0.194543,0.072373,0.156312,0.026684,0.333483,0.845122
6,169342391876059241,4,2,2,bogus,VS,VS,0.163532,0.049150,0.158930,0.043151,0.284267,0.611685,0.159111,0.043376,0.234160,0.252638
7,169342391882874888,4,4,4,bogus,bogus,bogus,0.153925,0.017867,0.153361,0.017571,0.174357,0.031543,0.153437,0.017611,0.364920,0.915408
8,169342391942644039,4,4,4,bogus,bogus,bogus,0.167876,0.049288,0.158468,0.037890,0.211458,0.141201,0.158713,0.038158,0.303484,0.733463
9,169342391999267256,4,4,4,bogus,bogus,bogus,0.159623,0.042712,0.158568,0.041441,0.235911,0.253630,0.158860,0.041789,0.287038,0.620427

In [5]:
rubin_stamp_test = stamps[
    (stamps.oid.isin(test_predictions.head(10).oid.values)) &
    (stamps.measurement_id.isin(test_predictions.head(10).measurement_id.values))
    ]

rubin_stamp_test

,oid,measurement_id,flux_Science_data,flux_Science_header,flux_Template_data,flux_Template_header,flux_Difference_data,flux_Difference_header,variance_Science_data,variance_Science_header,variance_Template_data,variance_Template_header,variance_Difference_data,variance_Difference_header,mask_Science_data,mask_Science_header,mask_Template_data,mask_Template_header,mask_Difference_data,mask_Difference_header
5,169342391479697434,169342391479697434,"[[2.8988338, -2.4290094, -0.40990388, 3.721083...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-2.1515293, -0.33305925, 3.2159805, -1.45036...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[3.1726909, -1.6475612, -0.40094173, 3.467754...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[102.51675, 100.10922, 100.06972, 102.78833, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[10.72114, 10.770189, 14.665173, 11.000376, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[116.728714, 114.01459, 114.32161, 117.0606, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.47...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.47...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
15,169342391520592115,169342391520592115,"[[5.556598, -3.667904, -8.657433, -0.8639773, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-1.5228868, -2.4966536, 1.6400974, 3.6343615...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[4.4742393, -3.809617, -8.149397, 0.62340635,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[102.0219, 98.32574, 95.61509, 99.17473, 96.6...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[13.306577, 12.519216, 12.182476, 14.382535, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[117.868324, 113.57324, 110.44294, 114.6966, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.70...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.70...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
16,169342391522689127,169364381640949779,"[[-4.828001, -0.24880087, -32.080284, -8.37708...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-6.589725, -9.097363, 9.243717, 3.0362973, 1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-1.542378, 4.8060017, -30.780264, -9.446799,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[595.2094, 598.8102, 578.8861, 593.4443, 598....","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[40.186935, 38.75196, 40.72997, 40.181877, 42...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[636.47943, 638.712, 620.6105, 634.70197, 642...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.93...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 5.230466737590419e-12, -4.70528284...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.93...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
17,169342391608147991,169342391608147991,"[[8.05567, -4.489069, 15.13296, -15.971238, 13...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-3.059267, 3.836855, 8.284468, -0.056010816,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[9.974397, -4.7797127, 15.711439, -17.189196,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[104.14571, 97.565636, 107.076004, 92.55198, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[14.556621, 14.651628, 15.640138, 12.231098, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[120.629974, 113.09305, 124.08029, 107.142365...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.24...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.24...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
24,169342391654809731,169342391654809731,"[[55.5184, 33.0449, 64.37901, 73.99079, 71.002...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[39.144352, 42.153557, 48.409412, 47.415943, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[13.240697, -16.484053, 8.053008, 12.111902, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[122.38404, 114.73953, 127.96685, 132.42072, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[14.087751, 15.32384, 14.1205635, 14.625894, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[138.41882, 130.06357, 144.64929, 149.68568, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.98...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.98...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
26,169342391672635395,169342391672635395,"[[1.8646865, -19.968048, 7.2650485, -6.6935225...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[3.575583, 3.7851143, -4.8485956, -3.3128796,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1.2292384, -22.086931, 8.732109, -6.4642873,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[114.716385, 104.35967, 116.66854, 110.479, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[13.89675, 13.736855, 11.979965, 12.765345, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[129.6693, 118.04331, 131.7172, 124.83402, 12...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.42...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.42...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
39,169342391876059241,169342391876059241,"[[-0.68717504, -0.4402154, 4.064196, 7.2790923...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-2.3817327, -4.2231584, -3.953232, 5.0926657...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1.679718, 1.8077652, 6.579378, 9.75328, -6.3...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[96.149055, 95.86962, 97.60847, 99.815834, 92...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[13.61771, 11.864436, 13.156809, 14.979106, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[112.33239, 111.87207, 113.9853, 116.68211, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.81...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.81...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
41,169342391882874888,169342391882874888,"[[20.677744, 4.8112636, -1.379793, 13.656979, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-0.38717267, 0.5723902, 6.320957, -1.4846599...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[16.834517, -0.013794899, -6.2448583, 10.6810...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[102.457085, 95.26164, 93.717995, 99.269226, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[11.215287, 11.184788, 14.871967, 12.651956, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[117.29714, 109.1133, 107.62003, 113.774414, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.03...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.03...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
45,169342391942644039,169342391942644039,"[[-9.77824, 7.6743646, -13.819823, 2.2708077, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-3.0829163, -2.7833352, -0.36756605, 8.36512...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-10.880029, 9.436494, -13.685192, 1.4765003,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[115.16547, 125.29295, 114.93973, 122.14404, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[18.942648, 13.925762, 13.027656, 20.546701, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[131.75795, 142.36688, 130.63976, 139.80872, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.18...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.18...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
48,169342391999267256,169368781117194308,"[[-11.690092, -8.071028, -13.6161585, -4.09803...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[4.683977, 1.5246886, -6.401027, 6.354101, -5...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[0.0, -8.641069, -14.685629, -4.721305, -8.02...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[164.80865, 168.15279, 164.01257, 168.13773, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[16.33895, 15.300511, 14.419867, 14.026656, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[182.30905, 186.00134, 181.41911, 185.97823, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.22...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.22...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."

In [6]:
rubin_stamp_test.columns

Index(['oid', 'measurement_id', 'flux_Science_data', 'flux_Science_header',
       'flux_Template_data', 'flux_Template_header', 'flux_Difference_data',
       'flux_Difference_header', 'variance_Science_data',
       'variance_Science_header', 'variance_Template_data',
       'variance_Template_header', 'variance_Difference_data',
       'variance_Difference_header', 'mask_Science_data',
       'mask_Science_header', 'mask_Template_data', 'mask_Template_header',
       'mask_Difference_data', 'mask_Difference_header'],
      dtype='object')

In [7]:
comm_objs_4candmax = pd.read_parquet('/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin/data/processed/ts_stamps_v0.0.2_comm_4candmax/comm_objs_4candmax.parquet')
comm_objs_4candmax

,oid,sid,measurement_id,class,mjd,ra,dec,band,visit,detector,...,shape_flag_parent_source,isDipole,pixelFlags_crCenter,pixelFlags_nodataCenter,pixelFlags_interpolatedCenter,pixelFlags_saturatedCenter,pixelFlags_suspectCenter,pixelFlags_streakCenter,pixelFlags_injectedCenter,pixelFlags_injected_templateCenter
0,169298432645136566,1,169298432645136566,AGN,60924.330414,8.905992,-44.103805,3,2025090500225,91,...,False,True,False,False,False,False,False,False,False,False
1,169298432645136566,1,169342390804939401,AGN,60934.116476,8.906227,-44.103605,1,2025091500059,43,...,False,False,False,False,False,False,False,False,False,False
2,169298432645136566,1,169342391077569156,AGN,60934.11739,8.906245,-44.103744,1,2025091500061,51,...,False,False,False,False,False,False,False,False,False,False
3,169298432645136566,1,169342391901225029,AGN,60934.120075,8.906182,-44.103707,1,2025091500067,86,...,False,False,False,False,False,False,False,False,False,False
4,169298436562092346,1,169298436562092346,AGN,60924.363906,9.721266,-43.055253,3,2025090500254,138,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6963,169623885986660770,1,169623885986660770,bogus,60998.222662,7.275447,-43.372673,2,2025111800209,181,...,False,False,False,False,False,False,False,False,False,False
6964,169623886050099223,1,169623886050099223,bogus,60998.223125,9.959908,-45.02071,2,2025111800210,46,...,False,False,False,False,False,False,False,False,False,False
6965,169623886051672110,1,169623886051672110,bogus,60998.223125,9.650085,-44.784965,2,2025111800210,49,...,False,False,False,False,False,False,False,False,False,False
6966,169623886096236648,1,169623886096236648,bogus,60998.223125,8.584275,-43.367622,2,2025111800210,134,...,False,False,False,False,False,False,False,False,False,False
6967,169623886116683891,1,169623886116683891,bogus,60998.223125,7.626684,-43.558806,2,2025111800210,173,...,False,False,False,False,False,False,False,False,False,False

In [8]:
resultado = pd.merge(
    rubin_stamp_test, 
    comm_objs_4candmax, 
    on=['oid', 'measurement_id'], 
    how='left'
)
resultado

,oid,measurement_id,flux_Science_data,flux_Science_header,flux_Template_data,flux_Template_header,flux_Difference_data,flux_Difference_header,variance_Science_data,variance_Science_header,...,shape_flag_parent_source,isDipole,pixelFlags_crCenter,pixelFlags_nodataCenter,pixelFlags_interpolatedCenter,pixelFlags_saturatedCenter,pixelFlags_suspectCenter,pixelFlags_streakCenter,pixelFlags_injectedCenter,pixelFlags_injected_templateCenter
0,169342391479697434,169342391479697434,"[[2.8988338, -2.4290094, -0.40990388, 3.721083...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-2.1515293, -0.33305925, 3.2159805, -1.45036...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[3.1726909, -1.6475612, -0.40094173, 3.467754...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[102.51675, 100.10922, 100.06972, 102.78833, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
1,169342391520592115,169342391520592115,"[[5.556598, -3.667904, -8.657433, -0.8639773, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-1.5228868, -2.4966536, 1.6400974, 3.6343615...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[4.4742393, -3.809617, -8.149397, 0.62340635,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[102.0219, 98.32574, 95.61509, 99.17473, 96.6...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
2,169342391522689127,169364381640949779,"[[-4.828001, -0.24880087, -32.080284, -8.37708...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-6.589725, -9.097363, 9.243717, 3.0362973, 1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-1.542378, 4.8060017, -30.780264, -9.446799,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[595.2094, 598.8102, 578.8861, 593.4443, 598....","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
3,169342391608147991,169342391608147991,"[[8.05567, -4.489069, 15.13296, -15.971238, 13...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-3.059267, 3.836855, 8.284468, -0.056010816,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[9.974397, -4.7797127, 15.711439, -17.189196,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[104.14571, 97.565636, 107.076004, 92.55198, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
4,169342391654809731,169342391654809731,"[[55.5184, 33.0449, 64.37901, 73.99079, 71.002...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[39.144352, 42.153557, 48.409412, 47.415943, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[13.240697, -16.484053, 8.053008, 12.111902, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[122.38404, 114.73953, 127.96685, 132.42072, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
5,169342391672635395,169342391672635395,"[[1.8646865, -19.968048, 7.2650485, -6.6935225...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[3.575583, 3.7851143, -4.8485956, -3.3128796,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1.2292384, -22.086931, 8.732109, -6.4642873,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[114.716385, 104.35967, 116.66854, 110.479, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
6,169342391876059241,169342391876059241,"[[-0.68717504, -0.4402154, 4.064196, 7.2790923...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-2.3817327, -4.2231584, -3.953232, 5.0926657...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1.679718, 1.8077652, 6.579378, 9.75328, -6.3...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[96.149055, 95.86962, 97.60847, 99.815834, 92...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
7,169342391882874888,169342391882874888,"[[20.677744, 4.8112636, -1.379793, 13.656979, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-0.38717267, 0.5723902, 6.320957, -1.4846599...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[16.834517, -0.013794899, -6.2448583, 10.6810...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[102.457085, 95.26164, 93.717995, 99.269226, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
8,169342391942644039,169342391942644039,"[[-9.77824, 7.6743646, -13.819823, 2.2708077, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-3.0829163, -2.7833352, -0.36756605, 8.36512...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-10.880029, 9.436494, -13.685192, 1.4765003,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[115.16547, 125.29295, 114.93973, 122.14404, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
9,169342391999267256,169368781117194308,"[[-11.690092, -8.071028, -13.6161585, -4.09803...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[4.683977, 1.5246886, -6.401027, 6.354101, -5...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[0.0, -8.641069, -14.685629, -4.721305, -8.02...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[164.80865, 168.15279, 164.01257, 168.13773, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False

In [9]:
resultado = resultado.rename(columns={
    'oid': 'diaObjectId',
    'measurement_id': 'diaSourceId',
    'flux_Science_data': 'visit_image',
    'flux_Template_data': 'reference_image',
    'flux_Difference_data': 'difference_image',
})

resultado

,diaObjectId,diaSourceId,visit_image,flux_Science_header,reference_image,flux_Template_header,difference_image,flux_Difference_header,variance_Science_data,variance_Science_header,...,shape_flag_parent_source,isDipole,pixelFlags_crCenter,pixelFlags_nodataCenter,pixelFlags_interpolatedCenter,pixelFlags_saturatedCenter,pixelFlags_suspectCenter,pixelFlags_streakCenter,pixelFlags_injectedCenter,pixelFlags_injected_templateCenter
0,169342391479697434,169342391479697434,"[[2.8988338, -2.4290094, -0.40990388, 3.721083...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-2.1515293, -0.33305925, 3.2159805, -1.45036...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[3.1726909, -1.6475612, -0.40094173, 3.467754...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[102.51675, 100.10922, 100.06972, 102.78833, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
1,169342391520592115,169342391520592115,"[[5.556598, -3.667904, -8.657433, -0.8639773, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-1.5228868, -2.4966536, 1.6400974, 3.6343615...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[4.4742393, -3.809617, -8.149397, 0.62340635,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[102.0219, 98.32574, 95.61509, 99.17473, 96.6...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
2,169342391522689127,169364381640949779,"[[-4.828001, -0.24880087, -32.080284, -8.37708...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-6.589725, -9.097363, 9.243717, 3.0362973, 1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-1.542378, 4.8060017, -30.780264, -9.446799,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[595.2094, 598.8102, 578.8861, 593.4443, 598....","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
3,169342391608147991,169342391608147991,"[[8.05567, -4.489069, 15.13296, -15.971238, 13...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-3.059267, 3.836855, 8.284468, -0.056010816,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[9.974397, -4.7797127, 15.711439, -17.189196,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[104.14571, 97.565636, 107.076004, 92.55198, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
4,169342391654809731,169342391654809731,"[[55.5184, 33.0449, 64.37901, 73.99079, 71.002...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[39.144352, 42.153557, 48.409412, 47.415943, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[13.240697, -16.484053, 8.053008, 12.111902, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[122.38404, 114.73953, 127.96685, 132.42072, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
5,169342391672635395,169342391672635395,"[[1.8646865, -19.968048, 7.2650485, -6.6935225...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[3.575583, 3.7851143, -4.8485956, -3.3128796,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1.2292384, -22.086931, 8.732109, -6.4642873,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[114.716385, 104.35967, 116.66854, 110.479, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
6,169342391876059241,169342391876059241,"[[-0.68717504, -0.4402154, 4.064196, 7.2790923...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-2.3817327, -4.2231584, -3.953232, 5.0926657...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1.679718, 1.8077652, 6.579378, 9.75328, -6.3...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[96.149055, 95.86962, 97.60847, 99.815834, 92...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
7,169342391882874888,169342391882874888,"[[20.677744, 4.8112636, -1.379793, 13.656979, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-0.38717267, 0.5723902, 6.320957, -1.4846599...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[16.834517, -0.013794899, -6.2448583, 10.6810...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[102.457085, 95.26164, 93.717995, 99.269226, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
8,169342391942644039,169342391942644039,"[[-9.77824, 7.6743646, -13.819823, 2.2708077, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-3.0829163, -2.7833352, -0.36756605, 8.36512...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-10.880029, 9.436494, -13.685192, 1.4765003,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[115.16547, 125.29295, 114.93973, 122.14404, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False
9,169342391999267256,169368781117194308,"[[-11.690092, -8.071028, -13.6161585, -4.09803...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[4.683977, 1.5246886, -6.401027, 6.354101, -5...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[0.0, -8.641069, -14.685629, -4.721305, -8.02...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[164.80865, 168.15279, 164.01257, 168.13773, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,False,False,False,False,False,False,False,False,False,False

In [10]:
resultado.columns

Index(['diaObjectId', 'diaSourceId', 'visit_image', 'flux_Science_header',
       'reference_image', 'flux_Template_header', 'difference_image',
       'flux_Difference_header', 'variance_Science_data',
       'variance_Science_header', 'variance_Template_data',
       'variance_Template_header', 'variance_Difference_data',
       'variance_Difference_header', 'mask_Science_data',
       'mask_Science_header', 'mask_Template_data', 'mask_Template_header',
       'mask_Difference_data', 'mask_Difference_header', 'sid', 'class', 'mjd',
       'ra', 'dec', 'band', 'visit', 'detector', 'snr', 'psfFlux',
       'psfFluxErr', 'scienceFlux', 'scienceFluxErr', 'extendedness',
       'reliability', 'bboxSize', 'centroid_flag', 'psfFlux_flag',
       'psfFlux_flag_edge', 'psfFlux_flag_noGoodPixels', 'forced_PsfFlux_flag',
       'forced_PsfFlux_flag_edge', 'forced_PsfFlux_flag_noGoodPixels',
       'shape_flag', 'shape_flag_no_pixels', 'shape_flag_not_contained',
       'shape_flag_parent_source', 'isDipole', 'pixelFlags_crCenter',
       'pixelFlags_nodataCenter', 'pixelFlags_interpolatedCenter',
       'pixelFlags_saturatedCenter', 'pixelFlags_suspectCenter',
       'pixelFlags_streakCenter', 'pixelFlags_injectedCenter',
       'pixelFlags_injected_templateCenter'],
      dtype='object')

In [11]:
resultado['psfFlux']

0    960.70135
1    681.12335
2     46827.42
3     662.6723
4   -812.44403
5    1144.9137
6    746.27075
7     731.7086
8    -951.4088
9    2039.5743
Name: psfFlux, dtype: double[pyarrow]

In [12]:
resultado.to_pickle('rubin_stamp_test.pkl')