In [1]:
%cd ..

/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin

In [2]:
import pandas as pd
import numpy as np
import glob

In [3]:
path_stamps = glob.glob('simulated_data/fakes/*.npy')
path_stamps

['simulated_data/fakes/611256378312376542_z_2024120800360_8_592913913020940296_z_2024111700354_4_0.33.npy',
 'simulated_data/fakes/609780833707896898_g_2024112900266_0_650018217640591465_g_2024112600116_4_0.88.npy',
 'simulated_data/fakes/611255691117605475_r_2024113000163_3_614437609048899879_r_2024112600305_1_0.74.npy',
 'simulated_data/fakes/611255622398132035_i_2024120300157_8_648363383921311853_i_2024112300236_6_0.90.npy',
 'simulated_data/fakes/609788117972430021_i_2024111900089_8_650018148921114792_i_2024112600128_5_0.57.npy',
 'simulated_data/fakes/611254454167020410_u_2024113000173_4_614437609048899610_u_2024120100460_7_0.40.npy',
 'simulated_data/fakes/611254454167020410_g_2024113000170_7_648366201419858478_g_2024120700172_2_0.88.npy',
 'simulated_data/fakes/609788942606153550_u_2024113000173_5_609782139377943544_u_2024113000174_7_0.83.npy',
 'simulated_data/fakes/611256447031856188_r_2024110800306_5_609782139377942804_r_2024113000163_8_0.62.npy',
 'simulated_data/fakes/611254248008597650_y_2024112000222_8_592914119179370901_y_2024111900349_2_0.29.npy',
 'simulated_data/fakes/609780833707896898_g_2024112900266_0_650018973554835776_g_2024112800182_1_0.25.npy',
 'simulated_data/fakes/609788117972430021_y_2024112000230_6_592914119179370901_y_2024111900349_2_0.55.npy',
 'simulated_data/fakes/609788255411390363_z_2024120900329_6_592913913020940296_z_2024111700354_4_0.50.npy',
 'simulated_data/fakes/609788942606159978_z_2024120700283_6_609782139377943986_z_2024120700338_3_0.50.npy',
 'simulated_data/fakes/609788873886679763_r_2024120300148_7_604062686048682644_r_2024120500023_3_0.60.npy',
 'simulated_data/fakes/611254660325448862_i_2024120300131_2_648372729770147940_i_2024112300236_2_0.80.npy',
 'simulated_data/fakes/611254454167020410_z_2024120900329_4_611254522886495591_z_2024120800375_0_0.47.npy',
 'simulated_data/fakes/609789492361963147_r_2024113000166_2_628768368727425436_r_2024121000393_8_0.53.npy',
 'simulated_data/fakes/611254248008598479_i_2024112900222_6_648365582944567431_i_2024112300245_1_0.50.npy',
 'simulated_data/fakes/609788942606161287_r_2024111900084_7_648366819895148573_r_2024112800163_6_0.32.npy',
 'simulated_data/fakes/609788805167199011_g_2024113000171_2_611255003922831024_g_2024112900281_5_0.75.npy',
 'simulated_data/fakes/611255691117605475_z_2024120900327_8_611257271665557523_z_2024120900331_2_0.21.npy',
 'simulated_data/fakes/609788117972432474_g_2024113000171_2_648364277274509609_g_2024112800173_8_0.92.npy',
 'simulated_data/fakes/611255622398138571_g_2024110800295_8_648366201419858478_g_2024120700172_2_0.18.npy',
 'simulated_data/fakes/611254454167030807_r_2024113000163_7_604064129157694738_r_2024120500024_1_0.26.npy',
 'simulated_data/fakes/609781589622148745_y_2024112000217_0_592914119179370901_y_2024111900349_2_0.29.npy',
 'simulated_data/fakes/609789492361963147_u_2024113000176_5_614437609048899610_u_2024120100460_7_0.82.npy',
 'simulated_data/fakes/609788117972432474_i_2024110800265_6_611255003922830967_i_2024112900275_2_0.54.npy',
 'simulated_data/fakes/611254248008598230_z_2024111700138_2_648366407578288506_z_2024120700156_0_1.00.npy',
 'simulated_data/fakes/611255622398134656_g_2024120100162_0_611255003922831024_g_2024112900281_5_0.74.npy',
 'simulated_data/fakes/611255622398134656_g_2024120100162_0_648367575809392994_g_2024112800182_5_0.26.npy',
 'simulated_data/fakes/611254660325448862_r_2024120600243_2_648365651664044103_r_2024112300226_1_1.00.npy',
 'simulated_data/fakes/611254385447553805_i_2024120300160_4_648364964469276964_i_2024112600127_8_0.25.npy',
 'simulated_data/fakes/609780764988422794_g_2024120900332_6_648368263004160125_g_2024112600122_5_0.17.npy',
 'simulated_data/fakes/609788736447724428_r_2024112700177_2_648374035440205974_r_2024112600103_5_1.00.npy',
 'simulated_data/fakes/611255141361798854_i_2024120300157_2_648364139835556167_i_2024112800184_6_0.44.npy',
 'simulated_data/fakes/611255759837083697_z_2024120900325_5_648365033188753833_z_2024120700160_3_0.08.npy',
 'simulated_data/fakes/609782208097430917_g_2024113000171_7_648370736905322701_g_2024112600118_5_1.00.npy',
 'simulated_data/fakes/611255622398132035_z_2024120700336_8_614437746487853390_z_2024120900472_4_0.64.npy',
 'simulated_data/fakes/611255691117605474_u_2024120100160_1_609782139377943570_u_2024113000176_8_0.11.npy',
 'simulated_data/fakes/611255278800752887_i_2024120300129_2_648367781967823096_i_2024112300242_3_0.75.npy',
 'simulated_data/fakes/611256515751335758_g_2024110800274_2_609782139377943160_g_2024112700188_7_0.25.npy',
 'simulated_data/fakes/609788942606161287_r_2024111900084_7_604064129157694758_r_2024120500026_7_1.00.npy',
 'simulated_data/fakes/611255759837083697_r_2024113000163_3_648372042575380516_r_2024120700179_5_0.21.npy',
 'simulated_data/fakes/609789492361963147_g_2024113000171_1_609788942606140958_g_2024112900266_3_0.81.npy',
 'simulated_data/fakes/611253560813832654_r_2024113000165_1_611253560813814797_r_2024120100173_5_0.55.npy',
 'simulated_data/fakes/611256584470805653_y_2024112000223_2_592914119179370901_y_2024111900349_2_0.17.npy',
 'simulated_data/fakes/611255691117611984_g_2024112700166_1_648363315201835095_g_2024112600115_8_0.91.npy',
 'simulated_data/fakes/611254454167020833_i_2024120300162_1_648363383921311853_i_2024112300236_6_0.10.npy',
 'simulated_data/fakes/609781658341610176_r_2024120300143_0_614437609048899658_r_2024120300100_0_0.80.npy',
 'simulated_data/fakes/611254248008597650_u_2024120100154_1_614431080698610870_u_2024120200338_1_0.33.npy',
 'simulated_data/fakes/611255141361789545_i_2024120300157_1_609789423642477521_i_2024112800121_2_0.89.npy',
 'simulated_data/fakes/609782345536379390_g_2024112900229_0_614431080698610905_g_2024120200340_2_0.89.npy',
 'simulated_data/fakes/609788942606153550_y_2024112000217_3_592916112044195962_y_2024112500296_5_0.46.npy',
 'simulated_data/fakes/611255072642320956_g_2024113000168_1_611253835691723868_g_2024120100193_8_0.33.npy',
 'simulated_data/fakes/609782276816912278_z_2024120900329_0_611254522886495613_z_2024120800404_0_0.57.npy',
 'simulated_data/fakes/609788942606153550_r_2024113000166_5_648372729770147859_r_2024112300213_2_0.43.npy',
 'simulated_data/fakes/611254454167020833_g_2024112700166_7_648363315201835095_g_2024112600115_8_0.73.npy',
 'simulated_data/fakes/611255759837083697_z_2024120900325_5_612929079095591353_z_2024120900471_6_0.58.npy',
 'simulated_data/fakes/611255278800752274_i_2024120300129_2_648366407578288380_i_2024112600135_3_0.80.npy',
 'simulated_data/fakes/609789492361967215_g_2024113000171_1_648372798489624918_g_2024112800176_1_0.80.npy',
 'simulated_data/fakes/611255622398137816_g_2024112800139_1_592913981740417050_g_2024120200085_5_1.00.npy',
 'simulated_data/fakes/609788117972431159_r_2024112700181_2_648372867209101548_r_2024112800168_1_0.40.npy',
 'simulated_data/fakes/611255622398138571_r_2024120300172_8_648367575809392947_r_2024112800166_8_0.20.npy',
 'simulated_data/fakes/611255965995517136_r_2024110800258_2_648372867209101548_r_2024112800168_1_1.00.npy',
 'simulated_data/fakes/609780764988422794_r_2024120100197_8_611255003922833171_r_2024120100166_1_0.82.npy',
 'simulated_data/fakes/611256378312375263_g_2024110800274_8_628768506166382801_g_2024120900408_5_0.83.npy',
 'simulated_data/fakes/611254385447553805_y_2024112000221_4_592914119179370901_y_2024111900349_2_0.17.npy',
 'simulated_data/fakes/611255759837085561_y_2024112000229_8_592914119179370901_y_2024111900349_2_0.50.npy',
 'simulated_data/fakes/611255691117605474_u_2024120100160_1_614431080698610870_u_2024120200338_1_1.00.npy',
 'simulated_data/fakes/611253698252783373_i_2024120300161_3_648365582944567523_i_2024112600127_5_0.25.npy',
 'simulated_data/fakes/611255691117605474_y_2024112000224_8_592916112044195962_y_2024112500296_5_0.89.npy',
 'simulated_data/fakes/611254385447553281_z_2024111700139_4_612929079095591353_z_2024120900471_6_0.73.npy',
 'simulated_data/fakes/611257134226611503_u_2024120100160_0_614431080698610870_u_2024120200338_1_0.20.npy',
 'simulated_data/fakes/611254385447553281_i_2024120300161_4_648366338858811593_i_2024112600127_4_0.08.npy',
 'simulated_data/fakes/611254935203368776_r_2024120100199_1_604063441962929304_r_2024120500025_4_0.75.npy',
 'simulated_data/fakes/611255897276044684_g_2024120300150_1_648368263004160125_g_2024112600122_5_0.67.npy',
 'simulated_data/fakes/611254935203368777_g_2024113000167_0_648365789102997624_g_2024112600119_6_0.42.npy',
 'simulated_data/fakes/611254454167021486_z_2024120900328_4_609789629800908890_z_2024120700324_3_1.00.npy',
 'simulated_data/fakes/611254591605981728_g_2024120300153_0_611255003922831024_g_2024112900281_5_1.00.npy',
 'simulated_data/fakes/611255622398137710_z_2024111700145_2_612929079095591353_z_2024120900471_6_0.40.npy',
 'simulated_data/fakes/609782208097431507_g_2024113000171_7_648365033188753746_g_2024112800177_7_0.67.npy',
 'simulated_data/fakes/611255141361800834_z_2024120800380_1_611254522886495609_z_2024120800387_3_0.50.npy',
 'simulated_data/fakes/609789423642488424_i_2024120300162_6_605447177346482253_i_2024112400276_1_0.33.npy',
 'simulated_data/fakes/611254454167021486_r_2024113000164_7_648364345993986096_r_2024112300222_3_0.45.npy',
 'simulated_data/fakes/611254454167030807_i_2024120300128_1_648364139835556167_i_2024112800184_6_1.00.npy',
 'simulated_data/fakes/611253492094348529_r_2024113000164_2_612929972448792512_r_2024121000517_3_0.47.npy',
 'simulated_data/fakes/609780833707896898_g_2024112900266_0_609782139377943160_g_2024112700188_7_0.06.npy',
 'simulated_data/fakes/611255691117605474_y_2024112000224_8_592914119179370901_y_2024111900349_2_0.26.npy',
 'simulated_data/fakes/611255691117605475_y_2024112000224_8_592914119179370901_y_2024111900349_2_0.21.npy',
 'simulated_data/fakes/611257134226611503_i_2024112900276_2_648373348245438787_i_2024112800187_8_0.16.npy',
 'simulated_data/fakes/609788255411390363_z_2024120900329_6_614437746487853390_z_2024120900472_4_0.39.npy',
 'simulated_data/fakes/609788186691912696_i_2024110800265_6_650018355079544929_i_2024112600132_3_0.30.npy',
 'simulated_data/fakes/611254454167030205_u_2024120100151_4_609782139377943544_u_2024113000174_7_0.67.npy',
 'simulated_data/fakes/609788117972430021_g_2024113000171_2_648364071116079297_g_2024112600115_6_0.47.npy',
 'simulated_data/fakes/611255691117612584_r_2024121000402_8_650018767396405322_r_2024112600106_2_0.86.npy',
 'simulated_data/fakes/611255759837090728_i_2024120300128_8_648364964469277207_i_2024112800189_7_0.62.npy',
 'simulated_data/fakes/609788942606153550_u_2024113000173_5_609782139377943544_u_2024113000172_8_0.42.npy',
 'simulated_data/fakes/611255141361789545_r_2024113000164_7_648364689591369909_r_2024112600104_4_0.40.npy',
 'simulated_data/fakes/611254935203368777_i_2024120300157_7_648365582944567523_i_2024112600127_5_0.09.npy',
 'simulated_data/fakes/611255141361798854_g_2024110800286_1_630406709772288470_g_2024121000374_4_1.00.npy',
 'simulated_data/fakes/609782345536379390_g_2024112900229_0_648365033188753746_g_2024112800177_7_0.47.npy',
 'simulated_data/fakes/609788117972432474_y_2024112000217_6_592914119179370901_y_2024111900349_2_1.00.npy',
 'simulated_data/fakes/611254935203368776_y_2024112000219_8_592914119179370901_y_2024111900349_2_0.33.npy',
 'simulated_data/fakes/609789492361963147_g_2024113000171_1_609788942606140958_g_2024112900266_3_0.38.npy',
 'simulated_data/fakes/609782208097433541_y_2024111900099_8_592916112044195962_y_2024112500296_5_0.79.npy',
 'simulated_data/fakes/609781589622148745_y_2024112000217_0_592916112044195962_y_2024112500296_5_0.71.npy',
 'simulated_data/fakes/611254935203366531_y_2024112000218_8_592916112044195962_y_2024112500296_5_0.75.npy',
 'simulated_data/fakes/611255141361789545_g_2024113000167_7_648372798489624918_g_2024112800176_1_0.20.npy',
 'simulated_data/fakes/611256447031856263_r_2024110800306_2_648374104159682585_r_2024112300212_8_0.86.npy',
 'simulated_data/fakes/609788117972430021_z_2024120900330_6_611254866483872654_z_2024120700277_8_0.85.npy',
 'simulated_data/fakes/611253492094348529_z_2024120900325_6_609789629800908883_z_2024120700315_4_0.20.npy',
 'simulated_data/fakes/611253766972259721_z_2024120700311_4_612928529339777217_z_2024120700486_6_0.75.npy',
 'simulated_data/fakes/611253492094350784_i_2024111900089_2_648364895749800081_i_2024112300245_4_0.44.npy',
 'simulated_data/fakes/609782345536379390_u_2024110900199_0_614439120877388319_u_2024120100460_5_0.84.npy',
 'simulated_data/fakes/609788117972430021_y_2024112000230_6_592914119179370901_y_2024111900349_2_0.18.npy',
 'simulated_data/fakes/609789492361963147_g_2024113000171_1_648365582944567543_g_2024112700084_5_0.06.npy',
 'simulated_data/fakes/609782276816911518_r_2024120300142_0_648366819895148598_r_2024112300216_6_0.67.npy',
 'simulated_data/fakes/609789492361963147_i_2024120300128_3_648372798489624951_i_2024112800192_1_0.94.npy',
 'simulated_data/fakes/611254179289120625_i_2024112700173_2_648374172879159620_i_2024112800183_4_0.75.npy',
 'simulated_data/fakes/611255622398132035_z_2024120700336_8_592913913020940296_z_2024111700354_4_0.55.npy',
 'simulated_data/fakes/611255210081268696_g_2024120500105_2_648364827030323406_g_2024112600115_3_0.80.npy',
 'simulated_data/fakes/611255691117612584_y_2024112000219_8_592916112044195962_y_2024112500296_5_0.60.npy',
 'simulated_data/fakes/611253560813834619_g_2024110800283_7_648367575809392994_g_2024112800182_5_0.80.npy',
 'simulated_data/fakes/609788805167199011_i_2024120300132_3_648364208555032719_i_2024112300245_7_0.91.npy',
 'simulated_data/fakes/611255691117605474_y_2024112000224_8_592914119179370901_y_2024111900349_2_0.58.npy',
 'simulated_data/fakes/609781520902672606_u_2024113000173_7_614439120877388319_u_2024120100460_5_0.50.npy',
 'simulated_data/fakes/611254522886506515_g_2024120300164_1_648365582944567543_g_2024112700084_5_0.80.npy',
 'simulated_data/fakes/611256515751335758_r_2024110800306_2_648366132700381232_r_2024112600109_2_0.60.npy',
 'simulated_data/fakes/609788117972431159_y_2024112000230_6_592916112044195962_y_2024112500296_5_1.00.npy',
 'simulated_data/fakes/611255622398134656_y_2024112000220_8_592914119179370901_y_2024111900349_2_0.80.npy',
 'simulated_data/fakes/611254248008597332_u_2024120100157_2_614439120877388319_u_2024120100460_5_0.67.npy',
 'simulated_data/fakes/611255210081267843_g_2024120300166_1_648367575809392994_g_2024112800182_5_0.57.npy',
 'simulated_data/fakes/609782208097433541_g_2024113000171_7_609788942606140958_g_2024112900266_3_0.50.npy',
 'simulated_data/fakes/611255622398132035_z_2024120700336_8_611254522886495591_z_2024120800375_0_0.45.npy',
 'simulated_data/fakes/611253492094348529_r_2024113000164_2_648366957334102102_r_2024112300223_7_0.29.npy',
 'simulated_data/fakes/609788873886679149_r_2024120300118_6_630407259528102880_r_2024120200216_0_1.00.npy',
 'simulated_data/fakes/611253835691742131_r_2024120300170_1_648367575809392947_r_2024112800166_8_0.60.npy',
 'simulated_data/fakes/611254454167021486_y_2024112000216_4_592914119179370901_y_2024111900349_2_0.60.npy',
 'simulated_data/fakes/609782208097433541_z_2024111700159_6_611254522886495613_z_2024120800403_3_0.50.npy',
 'simulated_data/fakes/609789492361967215_y_2024112000224_6_592914119179370901_y_2024111900349_2_0.50.npy',
 'simulated_data/fakes/611254454167030807_r_2024113000163_7_648366338858811574_r_2024112600109_4_0.53.npy',
 'simulated_data/fakes/609782208097433541_z_2024111700159_6_648366407578288506_z_2024120700156_0_0.19.npy',
 'simulated_data/fakes/611256447031856263_g_2024120300150_2_611255003922831024_g_2024112900281_5_1.00.npy',
 'simulated_data/fakes/611255759837083697_i_2024120300159_5_650018836115882078_i_2024112300243_1_0.92.npy',
 'simulated_data/fakes/611254454167021486_u_2024113000173_4_609782139377943544_u_2024113000172_8_0.10.npy',
 'simulated_data/fakes/611255828556561422_r_2024120300174_2_648364002396602554_r_2024120700179_6_0.71.npy',
 'simulated_data/fakes/609782276816912278_r_2024112800144_8_628768987202715722_r_2024121000368_2_0.33.npy',
 'simulated_data/fakes/609782208097430917_i_2024112900275_0_648370736905322959_i_2024112800184_8_0.40.npy',
 'simulated_data/fakes/609780833707901751_g_2024120900332_3_650018217640591465_g_2024112600116_4_0.60.npy',
 'simulated_data/fakes/611254935203368777_z_2024120900325_7_611257271665557522_z_2024120900331_2_0.40.npy',
 'simulated_data/fakes/611254385447553805_y_2024112000221_4_592914119179370901_y_2024111900349_2_1.00.npy',
 'simulated_data/fakes/611254660325448862_i_2024120300131_2_648364827030323457_i_2024112600130_3_0.40.npy',
 'simulated_data/fakes/611253492094350784_y_2024111900094_2_592916112044195962_y_2024112500296_5_1.00.npy',
 'simulated_data/fakes/609781452183194824_g_2024112700185_7_648363315201835095_g_2024112600115_8_0.60.npy',
 'simulated_data/fakes/611255759837083697_z_2024120900325_5_609789629800908890_z_2024120700324_3_0.17.npy',
 'simulated_data/fakes/609788805167199011_g_2024113000171_2_648364071116079297_g_2024112600115_6_0.67.npy',
 'simulated_data/fakes/609781452183194824_r_2024120100196_7_604063441962929304_r_2024120500025_4_1.00.npy',
 'simulated_data/fakes/611256447031856188_r_2024110800306_5_628768987202715722_r_2024121000368_2_0.25.npy',
 'simulated_data/fakes/611254179289118414_g_2024112800132_2_609782139377943160_g_2024112700188_7_1.00.npy',
 'simulated_data/fakes/611254522886506515_r_2024120300173_1_648364208555032984_r_2024120700184_8_0.80.npy',
 'simulated_data/fakes/611254454167030807_u_2024120100160_7_614439120877388319_u_2024120100460_5_0.71.npy',
 'simulated_data/fakes/609788255411390363_g_2024113000171_5_650018973554835776_g_2024112800182_1_0.74.npy',
 'simulated_data/fakes/611255759837090728_y_2024112000223_8_592916112044195962_y_2024112500296_5_0.50.npy',
 'simulated_data/fakes/611254935203368776_y_2024112000219_8_592914119179370901_y_2024111900349_2_0.78.npy',
 'simulated_data/fakes/609788255411390363_u_2024113000173_5_614439120877388319_u_2024120100460_5_0.93.npy',
 'simulated_data/fakes/609789492361963147_r_2024113000166_2_648364002396602554_r_2024120700179_6_0.18.npy',
 'simulated_data/fakes/611255691117612584_g_2024113000168_0_648372798489624918_g_2024112800176_1_0.29.npy',
 'simulated_data/fakes/609788186691912317_i_2024120500064_6_648366407578288380_i_2024112600135_3_1.00.npy',
 'simulated_data/fakes/611254248008601221_g_2024120300119_7_592913981740417050_g_2024120200085_5_0.50.npy',
 'simulated_data/fakes/609788186691912696_z_2024120700329_6_614437746487853390_z_2024120900472_4_0.44.npy',
 'simulated_data/fakes/611255691117605474_r_2024120100199_0_648364071116079267_r_2024112600104_4_0.37.npy',
 'simulated_data/fakes/609781658341610176_r_2024120300143_0_648367575809392947_r_2024112800166_8_1.00.npy',
 'simulated_data/fakes/611254522886507897_u_2024120100151_7_609782139377943544_u_2024113000172_8_0.25.npy',
 'simulated_data/fakes/611255072642322579_z_2024120700267_2_614437746487853390_z_2024120900472_4_0.67.npy',
 'simulated_data/fakes/609781520902672606_g_2024113000167_8_648368125565206567_g_2024112600116_5_0.71.npy',
 'simulated_data/fakes/609780764988422794_r_2024120100197_8_648364208555032984_r_2024120700184_8_0.55.npy',
 'simulated_data/fakes/611256447031856263_i_2024120300133_8_648364689591369810_i_2024112600126_4_0.86.npy',
 'simulated_data/fakes/611254935203371842_y_2024112000232_8_592914119179370901_y_2024111900349_2_0.67.npy',
 'simulated_data/fakes/611255622398132035_u_2024113000175_0_609782139377943544_u_2024113000174_7_0.60.npy',
 'simulated_data/fakes/609780764988422794_u_2024120100158_8_609782139377943570_u_2024113000176_8_1.00.npy',
 'simulated_data/fakes/609788186691914789_r_2024120300170_3_648364071116079487_r_2024120700179_6_0.67.npy',
 'simulated_data/fakes/611253492094348529_g_2024112700168_2_611253835691723482_g_2024120100148_8_0.53.npy',
 'simulated_data/fakes/609782139377954411_i_2024120300156_4_609789423642477521_i_2024112800121_2_1.00.npy',
 'simulated_data/fakes/611255691117605475_i_2024120300159_8_650018286360068215_i_2024112600132_4_0.68.npy',

In [4]:
def parse_filename(filepath):
    """
    Extrae los metadatos del nombre de archivo según la convención del README.
    Devuelve un diccionario con los metadatos.
    """
    try:
        # 1. Obtiene solo el nombre del archivo, sin la ruta ni la extensión.
        # e.g., '.../file.npy' -> 'file'
        base_name = os.path.splitext(os.path.basename(filepath))[0]
        
        # 2. Divide el nombre del archivo por el guion bajo '_'
        parts = base_name.split('_')
        
        # 3. Asigna cada parte a su campo correspondiente, convirtiendo a número si es necesario.
        metadata = {
            'gal_objectId': parts[0],
            'gal_band': parts[1],
            'gal_visit': parts[2],
            'gal_detector': int(parts[3]),
            'diff_sourceId': parts[4],
            'diff_band': parts[5],
            'diff_visit': parts[6],
            'diff_detector': int(parts[7]),
            'SN_ellip_dist': float(parts[8]),
        }
        return metadata
    except (IndexError, ValueError) as e:
        print(f"ADVERTENCIA: No se pudo parsear el nombre del archivo: {filepath}. Error: {e}")
        return None

In [5]:
import numpy as np
import os

data_rows = []

# 2. Iteramos sobre cada path en la lista
for path in path_stamps:
    # Primero, extraemos los metadatos del nombre del archivo
    metadata = parse_filename(path)
    
    # Si el parseo falló, saltamos este archivo
    if metadata is None:
        continue

    # Cargamos los datos de imagen del archivo .npy
    loaded_data = np.load(path)
    science_data = loaded_data[:,:,0]
    template_data = loaded_data[:,:,1]
    difference_data = loaded_data[:,:,2]
    
    # Creamos un diccionario para la fila, combinando metadatos y datos de imagen
    row = {
        **metadata,  # Desempaqueta el diccionario de metadatos aquí
        'flux_Science_data': science_data,
        'flux_Difference_data': difference_data,
        'flux_Template_data': template_data,
        'original_path': path
    }
    
    data_rows.append(row)

# 3. Creamos el DataFrame final
df = pd.DataFrame(data_rows)
df

,gal_objectId,gal_band,gal_visit,gal_detector,diff_sourceId,diff_band,diff_visit,diff_detector,SN_ellip_dist,flux_Science_data,flux_Difference_data,flux_Template_data,original_path
0,611256378312376542,z,2024120800360,8,592913913020940296,z,2024111700354,4,0.33,"[[10.982742, -100.364624, -26.70795, 150.41075...","[[32.616245, -31.05905, -51.33175, 83.870514, ...","[[-21.633503, -69.30557, 24.623798, 66.54024, ...",simulated_data/fakes/611256378312376542_z_2024...
1,609780833707896898,g,2024112900266,0,650018217640591465,g,2024112600116,4,0.88,"[[210.51036, 194.16635, 226.60606, 208.87112, ...","[[4.6535196, -7.1084204, 15.935069, -5.0868855...","[[205.85684, 201.27477, 210.67099, 213.95801, ...",simulated_data/fakes/609780833707896898_g_2024...
2,611255691117605475,r,2024113000163,3,614437609048899879,r,2024112600305,1,0.74,"[[-24.263647, 23.363667, -8.025528, 55.17688, ...","[[-10.19281, 19.809084, -1.9615426, 28.060669,...","[[-14.070837, 3.5545833, -6.063985, 27.116209,...",simulated_data/fakes/611255691117605475_r_2024...
3,611255622398132035,i,2024120300157,8,648363383921311853,i,2024112300236,6,0.90,"[[60.298386, -91.77385, 44.987007, -35.799484,...","[[37.04548, -36.984486, 48.095524, -9.511111, ...","[[23.252905, -54.789364, -3.108515, -26.288372...",simulated_data/fakes/611255622398132035_i_2024...
4,609788117972430021,i,2024111900089,8,650018148921114792,i,2024112600128,5,0.57,"[[64.394684, 132.19717, -14.009651, 126.18045,...","[[-16.556696, 32.335075, -49.94117, 25.10089, ...","[[80.95138, 99.86209, 35.93152, 101.07956, 159...",simulated_data/fakes/609788117972430021_i_2024...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4494,609788117972430021,r,2024112700181,2,611255003922833171,r,2024120100166,1,0.21,"[[30.381765, 45.401703, 87.44647, 67.1788, 52....","[[2.8186321, 15.799248, 9.838856, 2.4180062, -...","[[27.563133, 29.602457, 77.60762, 64.760796, 7...",simulated_data/fakes/609788117972430021_r_2024...
4495,611253698252783373,y,2024112000234,4,592914119179370901,y,2024111900349,2,1.00,"[[437.34286, 52.55536, -83.57059, -344.83063, ...","[[280.84787, -283.5208, -74.24422, -102.43766,...","[[156.495, 336.07617, -9.32637, -242.39296, -8...",simulated_data/fakes/611253698252783373_y_2024...
4496,611253560813832654,z,2024120900325,6,611254522886495613,z,2024120800404,0,0.30,"[[476.7009, 839.6953, 672.64343, 893.20953, 97...","[[-58.543423, 141.92401, -47.66682, 78.778076,...","[[535.2443, 697.7713, 720.31024, 814.43146, 96...",simulated_data/fakes/611253560813832654_z_2024...
4497,609781589622141692,i,2024120300155,0,648367507089916359,i,2024112800183,3,1.00,"[[-14.031038, 54.82399, -7.4305515, 7.14402, -...","[[5.214042, 29.72688, -21.895369, -33.847218, ...","[[-19.24508, 25.09711, 14.464817, 40.991238, 3...",simulated_data/fakes/609781589622141692_i_2024...
4498,611254660325448862,i,2024120300131,2,650018836115882058,i,2024112300235,0,0.27,"[[36.670353, 42.500847, 35.818367, 47.316467, ...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[36.670353, 42.500847, 35.818367, 47.316467, ...",simulated_data/fakes/611254660325448862_i_2024...

In [6]:
df_sinteticos = df[df.SN_ellip_dist < 0.5].rename(columns={'gal_band': 'band'})
df_sinteticos

,gal_objectId,band,gal_visit,gal_detector,diff_sourceId,diff_band,diff_visit,diff_detector,SN_ellip_dist,flux_Science_data,flux_Difference_data,flux_Template_data,original_path
0,611256378312376542,z,2024120800360,8,592913913020940296,z,2024111700354,4,0.33,"[[10.982742, -100.364624, -26.70795, 150.41075...","[[32.616245, -31.05905, -51.33175, 83.870514, ...","[[-21.633503, -69.30557, 24.623798, 66.54024, ...",simulated_data/fakes/611256378312376542_z_2024...
5,611254454167020410,u,2024113000173,4,614437609048899610,u,2024120100460,7,0.40,"[[49.542225, -8.923589, 75.038475, 37.86905, 4...","[[12.643394, 14.074204, 75.52924, 33.123417, 3...","[[36.89883, -22.997793, -0.4907656, 4.745632, ...",simulated_data/fakes/611254454167020410_u_2024...
9,611254248008597650,y,2024112000222,8,592914119179370901,y,2024111900349,2,0.29,"[[-45.61441, -393.84644, -204.19164, 696.6609,...","[[45.485214, -429.63184, -337.47598, 626.48224...","[[-91.099625, 35.785393, 133.28435, 70.17868, ...",simulated_data/fakes/611254248008597650_y_2024...
10,609780833707896898,g,2024112900266,0,650018973554835776,g,2024112800182,1,0.25,"[[15.538968, -19.373951, 10.069845, -6.252184,...","[[9.218049, -20.889612, -12.756815, -26.5888, ...","[[6.320919, 1.5156616, 22.82666, 20.336617, 9....",simulated_data/fakes/609780833707896898_g_2024...
16,611254454167020410,z,2024120900329,4,611254522886495591,z,2024120800375,0,0.47,"[[-22.330448, 35.378563, -0.542408, 17.049633,...","[[-21.24968, 9.9037285, -36.221664, -5.6041913...","[[-1.0807679, 25.474833, 35.679256, 22.653824,...",simulated_data/fakes/611254454167020410_z_2024...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4489,609782208097430917,y,2024111900099,8,592916112044195962,y,2024112500296,5,0.30,"[[343.73096, 312.34692, 690.9741, 386.07388, 4...","[[-92.50152, -33.328888, 56.65369, -323.34415,...","[[436.23248, 345.6758, 634.32043, 709.418, 546...",simulated_data/fakes/609782208097430917_y_2024...
4492,611255828556561422,i,2024120300157,2,648365651664044133,i,2024112300241,1,0.29,"[[35.547897, -40.608704, 38.428497, 15.815075,...","[[-3.844152, -26.865538, -25.571295, 9.694095,...","[[39.392048, -13.743167, 63.99979, 6.1209807, ...",simulated_data/fakes/611255828556561422_i_2024...
4494,609788117972430021,r,2024112700181,2,611255003922833171,r,2024120100166,1,0.21,"[[30.381765, 45.401703, 87.44647, 67.1788, 52....","[[2.8186321, 15.799248, 9.838856, 2.4180062, -...","[[27.563133, 29.602457, 77.60762, 64.760796, 7...",simulated_data/fakes/609788117972430021_r_2024...
4496,611253560813832654,z,2024120900325,6,611254522886495613,z,2024120800404,0,0.30,"[[476.7009, 839.6953, 672.64343, 893.20953, 97...","[[-58.543423, 141.92401, -47.66682, 78.778076,...","[[535.2443, 697.7713, 720.31024, 814.43146, 96...",simulated_data/fakes/611253560813832654_z_2024...
4498,611254660325448862,i,2024120300131,2,650018836115882058,i,2024112300235,0,0.27,"[[36.670353, 42.500847, 35.818367, 47.316467, ...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[36.670353, 42.500847, 35.818367, 47.316467, ...",simulated_data/fakes/611254660325448862_i_2024...

In [7]:
df_sinteticos.gal_objectId.nunique()

150

In [8]:
df_sinteticos.diff_sourceId.nunique()

247

In [9]:
for index, row in df_sinteticos[['band', 'diff_band']].iterrows():
    if row['band'] != row['diff_band']:
        print(f'Fila {index}: estamos mal - band: {row["band"]}, diff_band: {row["diff_band"]}')

In [10]:
path_real_stamps_v001 = glob.glob('./data/processed/ts_stamps_v0.0.1_comm_4candmax/stamps/*.pkl')

df_real_all_stamps_v001 = []

for path in path_real_stamps_v001:
    df_real_all_stamps_v001.append(pd.read_pickle(path))

df_real_all_stamps_v001 = pd.concat(df_real_all_stamps_v001)
df_real_all_stamps_v001

,oid,measurement_id,flux_Science_data,flux_Science_header,flux_Template_data,flux_Template_header,flux_Difference_data,flux_Difference_header,variance_Science_data,variance_Science_header,...,mask_Template_data,mask_Template_header,mask_Difference_data,mask_Difference_header,class_x,class_y,class,psfFlux,ra,dec
0,169342395216822494,169342395216822494,"[[-29.90286, 20.050756, -24.448586, 37.9608, 1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[12.407059, 1.2380395, 5.2192917, -2.3418732,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-42.505054, 13.39961, -36.91224, 33.745564, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[749.8122, 781.7552, 750.5761, 789.218, 773.4...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.29...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",bogus,bogus,bogus,1794.719971,305.623329,-22.201292
1,169342395222589770,169342395222589770,"[[6.0892243, 41.692726, 20.464373, 38.24141, 5...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[8.858687, 3.949492, 9.812762, 24.611567, 8.0...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-4.155531, 38.25864, 18.45956, 36.588226, -4...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[773.43225, 791.3081, 771.57007, 786.2522, 76...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.07...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",bogus,bogus,bogus,-2347.967529,305.24083,-21.746045
2,169342395228356610,169342395228356610,"[[2.3531318, 2.3519564, 2.3508527, 2.349675, 2...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[8.5377245, 16.045135, 5.262491, -15.194391, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[0.18315524, 1.1887197, 2.2256584, 2.8329298,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[702.817, 702.817, 702.817, 702.817, 702.817,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.89...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",bogus,bogus,bogus,-10584.624023,307.11691,-22.138993
3,169342395236745501,169342395236745501,"[[-13.643683, -9.305476, -35.914104, -7.162728...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[4.5434065, 17.43689, 5.001696, 7.8263507, 12...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-23.46883, -20.267704, -49.50765, -16.440329...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[698.37286, 700.87274, 682.6204, 703.06885, 7...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.13...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",bogus,bogus,bogus,-1972.344849,306.248979,-21.58878
4,169342395237269506,169342395237269506,"[[22.899294, 55.595303, -20.643349, 35.534683,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-14.037495, -3.1126611, -17.753826, 0.093163...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[27.705294, 59.402344, -28.094788, 29.818535,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[738.0622, 773.3888, 716.7294, 750.46564, 742...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.22...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",bogus,bogus,bogus,-2180.706299,306.023528,-21.46169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,169368791060840574,169368791060840574,"[[102.70164, 113.39593, 128.75226, 138.03426, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[37.595463, 27.04625, 33.29723, 46.658382, 25...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[22.23319, 19.229193, 19.179884, 11.544113, 5...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[985.0241, 988.644, 991.83795, 992.1794, 1039...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.34...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",bogus,bogus,bogus,3030.725342,316.915881,-13.756007
96,169368791085482037,169368791085482037,"[[-14.557428, -0.11440203, 40.64548, -43.92277...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1.9759903, 12.637623, -4.42347, 5.303948, 3....","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-23.234516, -7.6940045, 35.74645, -53.327168...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[888.0684, 896.1969, 920.57477, 870.2326, 898...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.47...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",bogus,bogus,bogus,2216.612305,317.741678,-13.541937
97,169368791086530689,169368791086530689,"[[-50.132732, -20.58231, 36.56712, -50.961586,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[7.9109073, 15.72925, 6.346818, -15.961184, 3...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-52.835297, -21.534258, 39.350876, -52.44798...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[884.2328, 897.9248, 936.3654, 882.1954, 889....","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.38...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",bogus,bogus,bogus,2239.009033,317.619737,-13.06321
98,169368791102259362,169368791102259362,"[[53.49603, 81.33197, 61.880768, 43.274117, 53...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[85.16669, 81.807526, 69.72638, 71.06515, 77....","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-30.197699, -3.2934394, -26.166256, -48.8950...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[977.77216, 1001.36005, 993.92523, 972.64703,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.36...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",bogus,bogus,bogus,-2772.981445,317.703204,-13.079414
99,169364391967326305,169364391967326305,"[[73.5812, 24.39516, -5.4876113, 2.374879, 19....","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-7.6503015, -1.3966511, 11.770005, 12.060944...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[79.32229, 26.767588, -5.1687703, 3.159387, 2...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1315.493, 1284.6656, 1270.1024, 1279.0548, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.08...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",satellite,satellite,satellite,3433.181885,305.896792,-23.163405

In [11]:
path_real_stamps = glob.glob('./data/processed/ts_stamps_v0.0.2_comm_4candmax/stamps/*.pkl')

df_real_all_stamps = []

for path in path_real_stamps:
    df_real_all_stamps.append(pd.read_pickle(path))

df_real_all_stamps = pd.concat(df_real_all_stamps)
df_real_all_stamps

,oid,measurement_id,flux_Science_data,flux_Science_header,flux_Template_data,flux_Template_header,flux_Difference_data,flux_Difference_header,variance_Science_data,variance_Science_header,variance_Template_data,variance_Template_header,variance_Difference_data,variance_Difference_header,mask_Science_data,mask_Science_header,mask_Template_data,mask_Template_header,mask_Difference_data,mask_Difference_header
0,169342391392665651,169368779404869680,"[[-11.43412, -61.157898, -36.767532, 2.3479912...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[19.970436, 9.456891, 13.70118, 1.8506378, 5....","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-19.709507, -70.71258, -45.61192, -5.388886,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1350.7681, 1316.2396, 1328.7379, 1375.7206, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[48.75372, 48.6074, 44.92881, 53.182293, 40.7...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[1406.3743, 1370.4304, 1383.4205, 1432.3733, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.69...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.69...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
1,169342391392665651,169368781154418723,"[[12.617219, 24.45698, 35.47745, 10.133407, 73...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[9.981423, 20.141548, 23.992834, 33.55316, 59...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-17.836555, -11.826263, -7.5156693, -41.9118...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[172.93977, 179.61725, 185.36595, 171.49901, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[13.86152, 13.508177, 13.792195, 13.8862915, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[189.61496, 196.93031, 203.23215, 188.03621, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.58...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -2.02857206888...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.58...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
2,169342391396859977,169342391396859977,"[[20.201748, 8.987029, 20.140661, 5.541897, 2....","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[11.899033, 14.724549, 8.104676, 9.156919, 10...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[9.553257, -0.75593305, 11.6207695, -3.399367...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[113.74172, 110.11547, 114.21119, 107.290985,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[12.621083, 12.107674, 12.1881275, 14.158052,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[128.269, 124.173134, 128.77019, 121.12555, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.33...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.33...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
3,169342391461347756,169342391461347756,"[[7.650416, 16.770666, 41.501934, 16.376083, 2...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[21.86371, 25.689003, 24.45363, 27.604593, 15...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-18.728577, -10.020834, 17.58616, -11.041704...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[118.146385, 123.34396, 135.7948, 123.88186, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[13.748417, 16.173056, 14.099533, 15.934614, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[133.68181, 139.71996, 153.50385, 140.3026, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.47...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.47...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
4,169342391478124608,169342391478124608,"[[-12.872995, 7.4767823, 3.0093896, -14.866771...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-0.6696128, -4.0996137, -1.7693138, 4.084112...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-13.231101, 9.655578, 5.3894978, -14.162557,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[95.70028, 106.682724, 105.2998, 97.141594, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[9.187543, 11.646914, 14.130292, 10.453682, 1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[108.53373, 121.11635, 119.7852, 110.2706, 11...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.92...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.92...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,169562329003328119,169562329003328119,"[[-3.0328236, -64.28421, -59.547096, -95.51208...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[0.4429303, -2.1661365, -3.942304, -1.5371937...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-3.2889779, -62.43242, -53.27369, -86.90933,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2748.3682, 2767.9216, 2761.9822, 2680.687, 2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[22.411716, 19.57459, 25.457203, 24.962057, 2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[2681.8643, 2697.5452, 2698.4775, 2619.3398, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.73...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.73...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
99,169562329013813258,169562329013813258,"[[38.172523, 26.093853, 12.283279, -20.133076,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[13.483821, -0.6748158, -1.7875571, -5.311088...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[36.14181, 21.505014, 15.589528, -20.170776, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2506.3015, 2492.8352, 2515.6287, 2466.9817, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[30.414555, 24.478794, 21.991266, 23.258093, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[2446.2385, 2429.4968, 2450.0212, 2403.6978, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.4...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.4...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
100,169562329013813258,169593100545032234,"[[14.314384, -34.407063, 11.400057, 25.750315,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1.7783704, 4.489515, 23.06503, 7.888879, -1....","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2.6454637, -26.03307, 30.09177, 30.84492, -1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[640.8675, 615.82117, 642.30597, 649.9814, 63...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[76.7588, 76.76051, 69.82708, 69.882355, 66.0...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[728.3893, 703.3576, 721.8941, 729.62885, 706...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.15...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[5.170419506124674e-13, -1.2015745476460523e-...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.15...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
101,169562329091932561,169562329091932561,"[[-3.8693318, 2.9912574, -13.400819, -4.486403...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-2.0172863, -2.326338, -4.0626445, -1.336142...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[6.1452055, 6.9367323, -3.1461492, 2.352298, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2793.3806, 2776.2332, 2761.9338, 2785.414, 2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[22.012081, 22.856272, 22.025944, 21.95137, 3...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[2762.5725, 2748.5422, 2732.255, 2754.7, 2798...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 2.2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 2.2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."
102,169562329102417949,169579900080488494,"[[71.2124, -59.137363, 7.426901, -32.388016, 3...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-15.60695, -13.921516, -21.890919, -16.37230...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[78.355125, -58.576157, 10.054412, -36.407543...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2951.7764, 2877.9316, 2949.492, 2871.1184, 2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[177.22978, 245.86554, 212.85515, 245.3349, 2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[3156.2275, 3082.4038, 3156.2983, 3075.11, 31...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.83...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.83...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU..."

In [12]:
df_real_all_stamps.columns

Index(['oid', 'measurement_id', 'flux_Science_data', 'flux_Science_header',
       'flux_Template_data', 'flux_Template_header', 'flux_Difference_data',
       'flux_Difference_header', 'variance_Science_data',
       'variance_Science_header', 'variance_Template_data',
       'variance_Template_header', 'variance_Difference_data',
       'variance_Difference_header', 'mask_Science_data',
       'mask_Science_header', 'mask_Template_data', 'mask_Template_header',
       'mask_Difference_data', 'mask_Difference_header'],
      dtype='object')

In [13]:
params = {
    "dbname": "ztf",
    "user": "readonly_user",
    "host": "quimal-db2.alerce.online",
    "password": "IvV)FhEDw",
    "port": 5432
}

import json
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy import text

import pandas as pd


engine = sa.create_engine('postgresql+psycopg2://' + params['user'] \
                          + ':' + params['password'] + '@' + params['host'] \
                          + '/' + params['dbname'])

conn = engine.connect()

inspector = inspect(engine)
tables = inspector.get_table_names()
print('Available Tables:\n', tables)

schemas = inspector.get_schema_names()

print("\nSchemas disponibles en la base de datos:")
print(schemas)

tables_rubin_schema = inspector.get_table_names(schema='multisurvey')

LSST_sid = 1

query = '''
SELECT
    *
FROM
    multisurvey.bands
'''
df_bands = pd.read_sql_query(text(query), conn)
dict_mapping = df_bands[df_bands.sid == LSST_sid].set_index('band')['band_name'].to_dict()
dict_mapping

Available Tables:
 []

Schemas disponibles en la base de datos:
['alerce', 'information_schema', 'multisurvey', 'multisurvey_testing', 'public']

{1: 'g', 2: 'r', 3: 'i', 4: 'z', 5: 'y', 6: 'u'}

In [14]:
df_real = pd.read_parquet('./data/processed/ts_stamps_v0.0.2_comm_4candmax/comm_objs_4candmax.parquet')
df_real.band = df_real.band.map(dict_mapping)
df_real

,oid,sid,measurement_id,class,mjd,ra,dec,band,visit,detector,...,shape_flag_parent_source,isDipole,pixelFlags_crCenter,pixelFlags_nodataCenter,pixelFlags_interpolatedCenter,pixelFlags_saturatedCenter,pixelFlags_suspectCenter,pixelFlags_streakCenter,pixelFlags_injectedCenter,pixelFlags_injected_templateCenter
0,169298432645136566,1,169298432645136566,AGN,60924.330414,8.905992,-44.103805,i,2025090500225,91,...,False,True,False,False,False,False,False,False,False,False
1,169298432645136566,1,169342390804939401,AGN,60934.116476,8.906227,-44.103605,g,2025091500059,43,...,False,False,False,False,False,False,False,False,False,False
2,169298432645136566,1,169342391077569156,AGN,60934.11739,8.906245,-44.103744,g,2025091500061,51,...,False,False,False,False,False,False,False,False,False,False
3,169298432645136566,1,169342391901225029,AGN,60934.120075,8.906182,-44.103707,g,2025091500067,86,...,False,False,False,False,False,False,False,False,False,False
4,169298436562092346,1,169298436562092346,AGN,60924.363906,9.721266,-43.055253,i,2025090500254,138,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6963,169623885986660770,1,169623885986660770,bogus,60998.222662,7.275447,-43.372673,r,2025111800209,181,...,False,False,False,False,False,False,False,False,False,False
6964,169623886050099223,1,169623886050099223,bogus,60998.223125,9.959908,-45.02071,r,2025111800210,46,...,False,False,False,False,False,False,False,False,False,False
6965,169623886051672110,1,169623886051672110,bogus,60998.223125,9.650085,-44.784965,r,2025111800210,49,...,False,False,False,False,False,False,False,False,False,False
6966,169623886096236648,1,169623886096236648,bogus,60998.223125,8.584275,-43.367622,r,2025111800210,134,...,False,False,False,False,False,False,False,False,False,False
6967,169623886116683891,1,169623886116683891,bogus,60998.223125,7.626684,-43.558806,r,2025111800210,173,...,False,False,False,False,False,False,False,False,False,False

In [15]:
# Por ejemplo, ordenar por mjd (fecha) y luego tomar el primer oid
#df_real = df_real.sort_values('mjd').drop_duplicates(subset=['oid'], keep='first')
#df_real

In [16]:
df_real.columns

Index(['oid', 'sid', 'measurement_id', 'class', 'mjd', 'ra', 'dec', 'band',
       'visit', 'detector', 'snr', 'psfFlux', 'psfFluxErr', 'scienceFlux',
       'scienceFluxErr', 'extendedness', 'reliability', 'bboxSize',
       'centroid_flag', 'psfFlux_flag', 'psfFlux_flag_edge',
       'psfFlux_flag_noGoodPixels', 'forced_PsfFlux_flag',
       'forced_PsfFlux_flag_edge', 'forced_PsfFlux_flag_noGoodPixels',
       'shape_flag', 'shape_flag_no_pixels', 'shape_flag_not_contained',
       'shape_flag_parent_source', 'isDipole', 'pixelFlags_crCenter',
       'pixelFlags_nodataCenter', 'pixelFlags_interpolatedCenter',
       'pixelFlags_saturatedCenter', 'pixelFlags_suspectCenter',
       'pixelFlags_streakCenter', 'pixelFlags_injectedCenter',
       'pixelFlags_injected_templateCenter'],
      dtype='object')

In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedGroupKFold
import os

# ==============================================================================
# 1. CONFIGURACIÓN
# ==============================================================================
PREVIOUS_PARTITIONS_PATH = "./partitions_trainSN_valSN_synthetic_dup.parquet"
DUPLICATES_FILE_PATH = "./data/processed/ts_stamps_v0.0.2_comm_4candmax/comm_agn_sne_vs_tran_dup_remove.csv" # <--- NUEVO
OUTPUT_PATH = "./partitions_trainSN_mixed_valSN_real_dup.parquet"

# Nombres de columnas
REAL_OID_COL = 'oid'
REAL_CANDID_COL = 'measurement_id'
SYNTHETIC_GAL_ID_COL = 'gal_objectId'
SYNTHETIC_DIFF_ID_COL = 'diff_sourceId'

FINAL_OID_COL = 'oid'
FINAL_CANDID_COL = 'measurement_id'
CLASS_COL = 'class'
GROUP_COL = 'group_id'
BAND_COL = 'band'
STRATIFY_COL = 'stratify_col'

DUP_OID_COL = 'oid'
DUP_OID_KEPT_COL = 'oid_kept'

N_FOLDS = 5
RANDOM_STATE = 42
TEST_SIZE = 0.2 

df_duplicates = pd.read_csv(DUPLICATES_FILE_PATH)

# ==============================================================================
# 3. ESTANDARIZACIÓN Y MANEJO DE DUPLICADOS
# ==============================================================================
print("Estandarizando...")

# --- Datos Reales ---
df_real.rename(columns={REAL_CANDID_COL: FINAL_CANDID_COL}, inplace=True)
df_real[FINAL_OID_COL] = df_real[REAL_OID_COL].astype(str)
df_real[FINAL_CANDID_COL] = df_real[FINAL_CANDID_COL].astype(str)
df_real['dataset_origin'] = 'real'

# Lógica de Duplicados (Aplica a TODAS las clases, incluidas SN)
dup_map = dict(zip(df_duplicates[DUP_OID_COL].astype(str), df_duplicates[DUP_OID_KEPT_COL].astype(str)))
df_real[GROUP_COL] = df_real[FINAL_OID_COL].map(dup_map).fillna(df_real[FINAL_OID_COL])

# --- Datos Sintéticos ---
df_sinteticos[CLASS_COL] = 'SN'
df_sinteticos.rename(columns={SYNTHETIC_GAL_ID_COL: FINAL_OID_COL, SYNTHETIC_DIFF_ID_COL: FINAL_CANDID_COL}, inplace=True)
df_sinteticos[FINAL_OID_COL] = df_sinteticos[FINAL_OID_COL].astype(str)
df_sinteticos[FINAL_CANDID_COL] = df_sinteticos[FINAL_CANDID_COL].astype(str)

if 'original_path' in df_sinteticos.columns:
    df_sinteticos[FINAL_CANDID_COL] = df_sinteticos['original_path'].apply(lambda x: os.path.splitext(os.path.basename(x))[0]).astype(str)
else:
    df_sinteticos[FINAL_CANDID_COL] = [f'FAKE_CANDID_{i}' for i in range(len(df_sinteticos))]

df_sinteticos[GROUP_COL] = df_sinteticos[FINAL_OID_COL]
df_sinteticos['dataset_origin'] = 'synthetic'

# Estratificación
df_real['stratify_col'] = df_real[CLASS_COL].astype(str) + '_' + df_real[BAND_COL].astype(str)
df_sinteticos['stratify_col'] = df_sinteticos[CLASS_COL].astype(str) + '_' + df_sinteticos[BAND_COL].astype(str)
STRATIFY_COL = 'stratify_col'


# ==============================================================================
# 4. LÓGICA DE TEST (Híbrida)
# ==============================================================================
print("\n--- Construyendo Test Set ---")
previous_partitions = pd.read_parquet(PREVIOUS_PARTITIONS_PATH)
# IDs del test anterior (NO-SN)
prev_test_ids = previous_partitions[previous_partitions['partition'] == 'test'][FINAL_CANDID_COL].unique()

# 1. Separar clases
df_real_sn = df_real[df_real[CLASS_COL] == 'SN'].copy()
df_real_non_sn = df_real[df_real[CLASS_COL] != 'SN'].copy()

# 2. Clases NO-SN: Mantener consistencia con IDs previos
#    (Los duplicados ya estaban manejados implícitamente si la partición previa fue correcta)
df_test_non_sn = df_real_non_sn[df_real_non_sn[FINAL_CANDID_COL].isin(prev_test_ids)].copy()
df_train_val_non_sn = df_real_non_sn[~df_real_non_sn[FINAL_CANDID_COL].isin(prev_test_ids)].copy()

# 3. Clase SN (REAL): Hacer nuevo Split 80/20 respetando duplicados
#    Usamos GROUP_COL para asegurar que los duplicados van juntos
unique_sn_groups = df_real_sn[GROUP_COL].unique()

# Estratificación simple por clase (ya que son todas SN) o aleatoria si hay pocos grupos
try:
    groups_train_val_sn, groups_test_sn = train_test_split(
        unique_sn_groups, 
        test_size=TEST_SIZE, 
        random_state=RANDOM_STATE
    )
except ValueError:
    print("Advertencia: Pocos grupos SN para split normal, usando random simple.")
    groups_train_val_sn, groups_test_sn = train_test_split(unique_sn_groups, test_size=TEST_SIZE, random_state=RANDOM_STATE)

df_test_sn = df_real_sn[df_real_sn[GROUP_COL].isin(groups_test_sn)].copy()
df_train_val_sn = df_real_sn[df_real_sn[GROUP_COL].isin(groups_train_val_sn)].copy()

# 4. Unir para TEST final
df_test = pd.concat([df_test_non_sn, df_test_sn], ignore_index=True)
df_test['partition'] = 'test'

# 5. Unir para Train/Val Pool REAL (Ahora incluye SN reales)
df_train_val_real = pd.concat([df_train_val_non_sn, df_train_val_sn], ignore_index=True)

print(f"Test Set: {len(df_test)} filas (SN Reales: {len(df_test_sn)})")
print(f"Train/Val Pool (Real): {len(df_train_val_real)} filas (SN Reales: {len(df_train_val_sn)})")


# ==============================================================================
# 5. K-FOLD (Estrategia Mixta Corregida)
# ==============================================================================
cols_to_save = [FINAL_OID_COL, FINAL_CANDID_COL, CLASS_COL, 'partition', 'dataset_origin']
partitions_list = [df_test[cols_to_save]]

# Datos Sintéticos (Solo para TRAINING)
df_train_synthetic = df_sinteticos.copy()

# K-Fold sobre datos REALES (SN y NO-SN)
X = df_train_val_real.index.to_numpy()
y = df_train_val_real[STRATIFY_COL].to_numpy()
groups = df_train_val_real[GROUP_COL].to_numpy()

sgkf = StratifiedGroupKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)

print(f"\nGenerando {N_FOLDS} folds...")

# Intentar estratificar, fallback a solo clase si falla
try:
    splitter = sgkf.split(X, y, groups=groups)
    next(splitter); splitter = sgkf.split(X, y, groups=groups)
except ValueError:
    print("Advertencia: Falló estratificación por clase+banda. Usando solo clase.")
    y = df_train_val_real[CLASS_COL].to_numpy()
    splitter = sgkf.split(X, y, groups=groups)

for fold_idx, (train_idx, val_idx) in enumerate(splitter):
    # 1. Datos Reales (SN y NO-SN)
    train_real = df_train_val_real.iloc[train_idx].copy()
    val_real = df_train_val_real.iloc[val_idx].copy()
    
    # 2. Inyectar Sintéticos (SN) -> SOLO EN TRAINING
    #    Ahora el training tiene: SN Reales + SN Sintéticas + Otras Clases Reales
    train_fold_combined = pd.concat([train_real, df_train_synthetic], ignore_index=True)
    
    # 3. Asignar etiquetas
    train_fold_combined['partition'] = f'training_{fold_idx}'
    val_real['partition'] = f'validation_{fold_idx}'
    
    partitions_list.extend([train_fold_combined[cols_to_save], val_real[cols_to_save]])

final_df = pd.concat(partitions_list, ignore_index=True)

# ==============================================================================
# Celda 6: Guardado y Verificación
# ==============================================================================
os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
final_df.to_parquet(OUTPUT_PATH, index=False)
print(f"\nArchivo guardado en: {OUTPUT_PATH}")

print("\n--- Resumen de Particiones ---")
print(final_df.groupby(['partition', 'dataset_origin']).size())

print("\n--- Verificaciones ---")
# Verificar que validación solo tenga reales
val_synthetic = final_df[
    (final_df['partition'].str.startswith('validation')) & 
    (final_df['dataset_origin'] == 'synthetic')
]
if len(val_synthetic) == 0:
    print("EXITO: No hay datos sintéticos en validación.")
else:
    print(f"ERROR: Se encontraron {len(val_synthetic)} datos sintéticos en validación.")

# Verificar fuga de OIDs reales entre train y val (Fold 0)
train_0_oids = set(final_df[(final_df['partition']=='training_0') & (final_df['dataset_origin']=='real')][FINAL_OID_COL])
val_0_oids = set(final_df[(final_df['partition']=='validation_0')][FINAL_OID_COL])
leak = train_0_oids.intersection(val_0_oids)
if len(leak) == 0:
    print("EXITO: No hay fuga de objetos reales entre Train_0 y Val_0.")
else:
    print(f"ERROR: Fuga detectada en {len(leak)} objetos.")

Estandarizando...

--- Construyendo Test Set ---
Test Set: 1356 filas (SN Reales: 35)
Train/Val Pool (Real): 5612 filas (SN Reales: 153)

Generando 5 folds...

/home/dmoreno/miniconda3/envs/stamp_rubin/lib/python3.10/site-packages/sklearn/model_selection/_split.py:1035: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/home/dmoreno/miniconda3/envs/stamp_rubin/lib/python3.10/site-packages/sklearn/model_selection/_split.py:1035: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

Archivo guardado en: ./partitions_trainSN_mixed_valSN_real_dup.parquet

--- Resumen de Particiones ---
partition     dataset_origin
test          real              1356
training_0    real              4470
              synthetic         1750
training_1    real              4509
              synthetic         1750
training_2    real              4520
              synthetic         1750
training_3    real              4441
              synthetic         1750
training_4    real              4508
              synthetic         1750
validation_0  real              1142
validation_1  real              1103
validation_2  real              1092
validation_3  real              1171
validation_4  real              1104
dtype: int64

--- Verificaciones ---
EXITO: No hay datos sintéticos en validación.
EXITO: No hay fuga de objetos reales entre Train_0 y Val_0.

In [24]:
OUTPUT_PATH

'./partitions_trainSN_mixed_valSN_real_dup.parquet'

In [25]:
import pandas as pd

partitions_poc = pd.read_parquet(f'{OUTPUT_PATH}')
#partitions_poc = pd.read_parquet(f'partitions_trainSN_mixed_valSN_real.parquet')
display(partitions_poc)

# Asumiendo que tu DataFrame se llama 'df'
conteo = partitions_poc.groupby(['partition', 'class']).size().reset_index(name='count')

# Para una visualización más clara, puedes pivotar la tabla
conteo_pivot = conteo.pivot(index='partition', columns='class', values='count').fillna(0)

print(conteo_pivot)

,oid,measurement_id,class,partition,dataset_origin
0,169302853145854613,169302853145854613,AGN,test,real
1,169302853145854613,169342391323459848,AGN,test,real
2,169302853145854613,169342391877108661,AGN,test,real
3,169302853145854613,169368781252985128,AGN,test,real
4,169302854308200461,169302854308200461,AGN,test,real
...,...,...,...,...,...
38161,169368775131398252,169368775131398252,SN,validation_4,real
38162,169368775131398252,169368781696532571,SN,validation_4,real
38163,169368775131398252,169368790533406737,SN,validation_4,real
38164,169368776457846868,169368776457846868,SN,validation_4,real
38165,169368786116804652,169368786116804652,SN,validation_4,real

class         AGN    SN   VS  asteroid  bogus
partition
test          247    35  218       432    424
training_0    815  1872  664      1468   1401
training_1    861  1876  653      1461   1408
training_2    884  1870  689      1462   1365
training_3    815  1860  643      1472   1401
training_4    869  1884  671      1441   1393
validation_0  246    31  166       358    341
validation_1  200    27  177       365    334
validation_2  177    33  141       364    377
validation_3  246    43  187       354    341
validation_4  192    19  159       385    349

In [26]:
partitions_poc.dtypes

oid               object
measurement_id    object
class             object
partition         object
dataset_origin    object
dtype: object

In [27]:
synthetic = partitions_poc[partitions_poc['dataset_origin'] == 'synthetic']
synthetic

,oid,measurement_id,class,partition,dataset_origin
5826,611256378312376542,611256378312376542_z_2024120800360_8_592913913...,SN,training_0,synthetic
5827,611254454167020410,611254454167020410_u_2024113000173_4_614437609...,SN,training_0,synthetic
5828,611254248008597650,611254248008597650_y_2024112000222_8_592914119...,SN,training_0,synthetic
5829,609780833707896898,609780833707896898_g_2024112900266_0_650018973...,SN,training_0,synthetic
5830,611254454167020410,611254454167020410_z_2024120900329_4_611254522...,SN,training_0,synthetic
...,...,...,...,...,...
37057,609782208097430917,609782208097430917_y_2024111900099_8_592916112...,SN,training_4,synthetic
37058,611255828556561422,611255828556561422_i_2024120300157_2_648365651...,SN,training_4,synthetic
37059,609788117972430021,609788117972430021_r_2024112700181_2_611255003...,SN,training_4,synthetic
37060,611253560813832654,611253560813832654_z_2024120900325_6_611254522...,SN,training_4,synthetic
37061,611254660325448862,611254660325448862_i_2024120300131_2_650018836...,SN,training_4,synthetic

In [28]:
training_0 = synthetic[synthetic['partition'] == 'training_0']
training_0

,oid,measurement_id,class,partition,dataset_origin
5826,611256378312376542,611256378312376542_z_2024120800360_8_592913913...,SN,training_0,synthetic
5827,611254454167020410,611254454167020410_u_2024113000173_4_614437609...,SN,training_0,synthetic
5828,611254248008597650,611254248008597650_y_2024112000222_8_592914119...,SN,training_0,synthetic
5829,609780833707896898,609780833707896898_g_2024112900266_0_650018973...,SN,training_0,synthetic
5830,611254454167020410,611254454167020410_z_2024120900329_4_611254522...,SN,training_0,synthetic
...,...,...,...,...,...
7571,609782208097430917,609782208097430917_y_2024111900099_8_592916112...,SN,training_0,synthetic
7572,611255828556561422,611255828556561422_i_2024120300157_2_648365651...,SN,training_0,synthetic
7573,609788117972430021,609788117972430021_r_2024112700181_2_611255003...,SN,training_0,synthetic
7574,611253560813832654,611253560813832654_z_2024120900325_6_611254522...,SN,training_0,synthetic
7575,611254660325448862,611254660325448862_i_2024120300131_2_650018836...,SN,training_0,synthetic

In [29]:
training_0.oid.nunique()

150

In [30]:
df_real

,oid,sid,measurement_id,class,mjd,ra,dec,band,visit,detector,...,pixelFlags_nodataCenter,pixelFlags_interpolatedCenter,pixelFlags_saturatedCenter,pixelFlags_suspectCenter,pixelFlags_streakCenter,pixelFlags_injectedCenter,pixelFlags_injected_templateCenter,dataset_origin,group_id,stratify_col
0,169298432645136566,1,169298432645136566,AGN,60924.330414,8.905992,-44.103805,i,2025090500225,91,...,False,False,False,False,False,False,False,real,169298432645136566,AGN_i
1,169298432645136566,1,169342390804939401,AGN,60934.116476,8.906227,-44.103605,g,2025091500059,43,...,False,False,False,False,False,False,False,real,169298432645136566,AGN_g
2,169298432645136566,1,169342391077569156,AGN,60934.11739,8.906245,-44.103744,g,2025091500061,51,...,False,False,False,False,False,False,False,real,169298432645136566,AGN_g
3,169298432645136566,1,169342391901225029,AGN,60934.120075,8.906182,-44.103707,g,2025091500067,86,...,False,False,False,False,False,False,False,real,169298432645136566,AGN_g
4,169298436562092346,1,169298436562092346,AGN,60924.363906,9.721266,-43.055253,i,2025090500254,138,...,False,False,False,False,False,False,False,real,169298436562092346,AGN_i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6963,169623885986660770,1,169623885986660770,bogus,60998.222662,7.275447,-43.372673,r,2025111800209,181,...,False,False,False,False,False,False,False,real,169623885986660770,bogus_r
6964,169623886050099223,1,169623886050099223,bogus,60998.223125,9.959908,-45.02071,r,2025111800210,46,...,False,False,False,False,False,False,False,real,169623886050099223,bogus_r
6965,169623886051672110,1,169623886051672110,bogus,60998.223125,9.650085,-44.784965,r,2025111800210,49,...,False,False,False,False,False,False,False,real,169623886051672110,bogus_r
6966,169623886096236648,1,169623886096236648,bogus,60998.223125,8.584275,-43.367622,r,2025111800210,134,...,False,False,False,False,False,False,False,real,169623886096236648,bogus_r
6967,169623886116683891,1,169623886116683891,bogus,60998.223125,7.626684,-43.558806,r,2025111800210,173,...,False,False,False,False,False,False,False,real,169623886116683891,bogus_r

In [31]:
partitions_poc

,oid,measurement_id,class,partition,dataset_origin
0,169302853145854613,169302853145854613,AGN,test,real
1,169302853145854613,169342391323459848,AGN,test,real
2,169302853145854613,169342391877108661,AGN,test,real
3,169302853145854613,169368781252985128,AGN,test,real
4,169302854308200461,169302854308200461,AGN,test,real
...,...,...,...,...,...
38161,169368775131398252,169368775131398252,SN,validation_4,real
38162,169368775131398252,169368781696532571,SN,validation_4,real
38163,169368775131398252,169368790533406737,SN,validation_4,real
38164,169368776457846868,169368776457846868,SN,validation_4,real
38165,169368786116804652,169368786116804652,SN,validation_4,real

In [33]:
import pandas as pd
import numpy as np
from astropy.coordinates import SkyCoord
from astropy import units as u

In [35]:
print("Datos cargados.")

# ==============================================================================
# 2. UNIR COORDENADAS CON PARTICIONES
# ==============================================================================
# Asegúrate de que la columna de ID se llame igual ('oid')
# Filtramos para tener solo una fila por objeto único (ya que las coords son por objeto)
df_analysis = pd.merge(partitions_poc, df_real, on='oid', how='inner')
# Si partitions tiene filas por detección, nos quedamos con una por objeto
df_analysis = df_analysis.drop_duplicates(subset=['oid']) 

print(f"Total de objetos únicos analizados: {len(df_analysis)}")

# ==============================================================================
# 3. FUNCIÓN DE ANÁLISIS DE VECINOS
# ==============================================================================
def analizar_vecinos_en_grupo(df_grupo, nombre_grupo):
    if len(df_grupo) < 2:
        return None
    
    # 1. Asegurar que RA y DEC sean numéricos (floats) y convertirlos a numpy arrays puros
    # Esto elimina cualquier metadata de PyArrow/Pandas que pueda causar conflicto
    ra_values = df_grupo['ra'].astype(float).to_numpy()
    dec_values = df_grupo['dec'].astype(float).to_numpy()
        
    # 2. Crear SkyCoord usando los arrays de numpy puros
    coords = SkyCoord(ra=ra_values * u.degree, 
                      dec=dec_values * u.degree)
    
    # Buscar 2do vecino más cercano
    idx, d2d, _ = coords.match_to_catalog_sky(coords, nthneighbor=2)
    
    # Crear resultado
    resultados = pd.DataFrame({
        'partition': nombre_grupo,
        'oid_1': df_grupo['oid'].values,
        'oid_2': df_grupo.iloc[idx]['oid'].values,
        'separation_arcsec': d2d.arcsec
    })
    
    # Ordenar y tomar el mínimo
    min_row = resultados.sort_values('separation_arcsec').iloc[0]
    return min_row

# ==============================================================================
# 4. EJECUCIÓN POR PARTICIÓN
# ==============================================================================
print("\n--- Resultados: Separación mínima por partición ---")

resultados_globales = []

# Iterar sobre cada partición única (training_0, validation_0, test, etc.)
for part_name in df_analysis['partition'].unique():
    # Filtrar datos de esa partición
    df_part = df_analysis[df_analysis['partition'] == part_name]
    
    # Calcular
    res = analizar_vecinos_en_grupo(df_part, part_name)
    
    if res is not None:
        resultados_globales.append(res)
        print(f"[{part_name}] Mínima separación: {res['separation_arcsec']:.6f} arcsec "
              f"(Entre {res['oid_1']} y {res['oid_2']})")

# ==============================================================================
# 5. RESUMEN FINAL
# ==============================================================================
if resultados_globales:
    df_final_results = pd.DataFrame(resultados_globales).sort_values('separation_arcsec')
    
    print("\n" + "="*60)
    print("RESUMEN GLOBAL (Ordenado por cercanía):")
    print(df_final_results)
    print("="*60)
    
    # Alerta crítica
    limite_alerta = 1.0 # arcsec
    muy_cercanos = df_final_results[df_final_results['separation_arcsec'] < limite_alerta]
    
    if not muy_cercanos.empty:
        print(f"\n⚠️ ADVERTENCIA: Se encontraron {len(muy_cercanos)} pares con separación < {limite_alerta}\" dentro de la misma partición.")
        print("Esto sugiere duplicados no resueltos que podrían afectar el entrenamiento/evaluación.")
    else:
        print(f"\n✅ Todo bien: No hay objetos extremadamente cercanos (< {limite_alerta}\") dentro de las particiones.")

Datos cargados.
Total de objetos únicos analizados: 4299

--- Resultados: Separación mínima por partición ---
[test] Mínima separación: 0.005081 arcsec (Entre 169562329369280585 y 169562329523421274)
[training_0] Mínima separación: 0.003061 arcsec (Entre 169342390926050043 y 169342391330275367)
[validation_0] Mínima separación: 0.003163 arcsec (Entre 169302853752455193 y 169302853103910941)

============================================================
RESUMEN GLOBAL (Ordenado por cercanía):
        partition               oid_1               oid_2  separation_arcsec
79     training_0  169342390926050043  169342391330275367           0.003061
104  validation_0  169302853752455193  169302853103910941           0.003163
236          test  169562329369280585  169562329523421274           0.005081
============================================================

⚠️ ADVERTENCIA: Se encontraron 3 pares con separación < 1.0" dentro de la misma partición.
Esto sugiere duplicados no resueltos que podrían afectar el entrenamiento/evaluación.

In [36]:
import pandas as pd
import numpy as np
from astropy.coordinates import SkyCoord, match_coordinates_sky
from astropy import units as u
import itertools

# ==============================================================================
# 1. CARGAR DATOS Y PREPARAR
# ==============================================================================
# ... (Asumiendo que df_analysis ya tiene 'oid', 'ra', 'dec', 'partition' cargados como antes) ...

print(f"Total de objetos únicos para analizar: {len(df_analysis)}")

# Función auxiliar para obtener coords de una partición
def get_coords(df, partition_name):
    subset = df[df['partition'] == partition_name]
    coords = SkyCoord(ra=subset['ra'].astype(float).to_numpy()*u.degree, 
                      dec=subset['dec'].astype(float).to_numpy()*u.degree)
    return coords, subset['oid'].to_numpy()

# ==============================================================================
# 2. CÁLCULO DE SEPARACIÓN ENTRE CONJUNTOS
# ==============================================================================
print("\n--- Análisis de Separación ENTRE Conjuntos (Busca fugas) ---")

# Definir los pares a comparar. 
# Queremos comparar cada fold de entrenamiento con su validación, y todo con test.
# Pero para simplificar y ver lo peor, compararemos todas las combinaciones posibles de particiones.

partition_names = df_analysis['partition'].unique()
# Generar todas las combinaciones de 2 particiones distintas
pairs = list(itertools.combinations(partition_names, 2))

resultados_cross = []

for part1, part2 in pairs:
    # Optimización: Solo nos interesa comparar Train vs Val del MISMO fold, o Train vs Test.
    # No tiene sentido comparar Training_0 con Validation_1, por ejemplo.
    
    es_train_val_mismo_fold = (part1.startswith('training_') and part2.replace('validation', 'training') == part1) or \
                              (part2.startswith('training_') and part1.replace('validation', 'training') == part2)
    
    es_con_test = ('test' in part1) or ('test' in part2)
    
    # Solo procesamos si es una comparación relevante para fuga de datos
    if es_train_val_mismo_fold or es_con_test:
        
        print(f"Comparando {part1} vs {part2}...")
        
        coords1, oids1 = get_coords(df_analysis, part1)
        coords2, oids2 = get_coords(df_analysis, part2)
        
        if len(coords1) == 0 or len(coords2) == 0:
            continue
            
        # match_coordinates_sky encuentra para cada objeto en coords1, el más cercano en coords2
        idx, d2d, _ = match_coordinates_sky(coords1, coords2)
        
        # Encontrar la mínima distancia en este cruce
        min_dist_idx = np.argmin(d2d)
        min_dist_arcsec = d2d[min_dist_idx].arcsec
        
        resultados_cross.append({
            'set_1': part1,
            'set_2': part2,
            'min_separation_arcsec': min_dist_arcsec,
            'oid_1': oids1[min_dist_idx],
            'oid_2': oids2[idx[min_dist_idx]]
        })

# ==============================================================================
# 3. RESULTADOS
# ==============================================================================
if resultados_cross:
    df_cross_results = pd.DataFrame(resultados_cross).sort_values('min_separation_arcsec')
    
    print("\n" + "="*80)
    print("RESUMEN DE SEPARACIÓN MÍNIMA ENTRE CONJUNTOS (Train vs Val / Train vs Test):")
    print(df_cross_results)
    print("="*80)
    
    # Alerta de Fuga
    limite_critico = 1.0 # arcsec (Si es menor a esto, probablemente es el mismo objeto)
    fugas = df_cross_results[df_cross_results['min_separation_arcsec'] < limite_critico]
    
    if not fugas.empty:
        print(f"\n🚨 ALERTA ROJA: Se encontraron {len(fugas)} pares de conjuntos con objetos a < {limite_critico}\".")
        print("Esto indica FUGA DE DATOS (Data Leakage). El mismo objeto físico está en ambos sets con distinto ID.")
        print(fugas)
    else:
        print(f"\n✅ EXCELENTE: La separación mínima entre conjuntos es > {limite_critico}\". No hay evidencia espacial de fuga de datos.")

Total de objetos únicos para analizar: 4299

--- Análisis de Separación ENTRE Conjuntos (Busca fugas) ---
Comparando test vs training_0...
Comparando test vs validation_0...
Comparando training_0 vs validation_0...

================================================================================
RESUMEN DE SEPARACIÓN MÍNIMA ENTRE CONJUNTOS (Train vs Val / Train vs Test):
        set_1         set_2  min_separation_arcsec               oid_1  \
2  training_0  validation_0               0.150800  169342391071801790
0        test    training_0               1.249692  169342391509582427
1        test  validation_0              14.087339  169342390827483268

                oid_2
2  169342390936011001
0  169355602395398209
1  169615082866081802
================================================================================

🚨 ALERTA ROJA: Se encontraron 1 pares de conjuntos con objetos a < 1.0".
Esto indica FUGA DE DATOS (Data Leakage). El mismo objeto físico está en ambos sets con distinto ID.
        set_1         set_2  min_separation_arcsec               oid_1  \
2  training_0  validation_0                 0.1508  169342391071801790

                oid_2
2  169342390936011001